### ISSUE TITLE
Consolidate `confidencesByIteratorLevel` and `characterBoxes`

### ISSUE THREAD

**Issue by ws233** [gali8/Tesseract-OCR-iOS#109]
If you try to run confidencesByIteratorLevel and characterChoices functions, after a tesseract finishes recognition, an app crasesh with the following:
best_choice != NULL:Error:Assert failed:in file ltrresultiterator.cpp, line 100

The tesseract is initialized with 
    G8Tesseract* tesseract1 = [[G8Tesseract alloc] initWithLanguage:@"rus+eng" engineMode:G8OCREngineModeTesseractOnly];

Also all the 'confidence' values in any G8RecognizedBlock of tesseracts characterChoices are 0s.

Is it a known issue?

**Comment by ws233** [comment]
With the last changes both functions work correct without any crashes.
Perhaps, something was wrong in the way I was using those functions.

Regarding reimplementation of the characterBoxes. It seems that it's just:
     - (NSArray *)characterBoxes {
         return [self confidencesByIteratorLevel:G8PageIteratorLevelSymbol];
     }

So, do we need this property actually? Perhaps it's more easy to understand the meaning then confidencesByIteratorLevel, so it should remain in the code.
What do you think?

Let's decide this, fix/don't fix and close.

**Comment by kevincon** [comment]
Hmm, it seems I can't assign you on GitHub because you have not been made a collaborator on the repo. I think you and @BamX should definitely be added as collaborators for all the work you have done. @gali8, what do you think?

**Comment by ws233** [comment]
What should we do for this? :)

**Comment by ws233** [comment]
And one more question.
What if we rename the function to recognizedBlocksByIteratorLevel to specify the type of the objects in the returned NSArray?

**Comment by kevincon** [comment]
Sure, `recognizedBlocksByIteratorLevel` sounds even better.

**Comment by ws233** [comment]
Here it is #124.
Pls, review.
