### ISSUE TITLE
sourceResolution question

### ISSUE THREAD

**Issue by ws233** [gali8/Tesseract-OCR-iOS#122]
1. sourceResolution never set to the upstream Tesseract without calls to setResolution. Is it ok? Is it a default value of the upstreamTesseract? I mean, in the setImage, setResolution setter is not called. so the value is only set to the instance variable and not set to the upstream Tesseract.
2. is 300dpi is the real value for all available Apple device cameras? I mean all of them starting from the very first iPhone. Should we consider different devices here and install corresponding value automatically recognizing the device on runtime?

**Comment by BamX** [comment]
We're setting 300dpi in convertion UIImage -> Pix by default. Not sure if it could be getted from UIImage. If developer know actual value he or she could set it up right to this property. We are usinig 7.0+ target, so that devices should have pretty good camera.
I could take a look about it tommorow.

**Comment by ws233** [comment]
Consider the following code:
        G8Tesseract* tesseract = [[G8Tesseract alloc] init];
        tesseract.delegate = self;
        tesseract.image = self.image;
        tesseract.sourceResolution = 72;

         - (UIImage *)preprocessedImageForTesseract:(G8Tesseract *)tesseract sourceImage:(UIImage *)sourceImage {
             return sourceImage;
        }

does sourceResolution = 72 affect something?

**Comment by BamX** [comment]
Sure, it setting local copy of ```sourceResolution``` and setting source resolution for Tesseract by calling ```SetSourceResolution()```. It happens after the image is setted, so everything should be ok.

**Comment by ws233** [comment]
hm... but what is the result of this? Nothing changed in the recognition results in my case.
Which values should I put to break the recognition process or make it better?

**Comment by BamX** [comment]
I don't know :) I've just implemented adaptor for such property. Not sure if it change something.
Here some code from ```baseapi```:
```
/**
 * Minimum believable resolution. Used as a default if there is no other
 * information, as it is safer to under-estimate than over-estimate.
 */
const int kMinCredibleResolution = 70;
/** Maximum believable resolution.  */
const int kMaxCredibleResolution = 2400;
```
By the way ```SetSourceResolution``` changes inner fields of Thresholder that initialized by setting image that how:
```estimated_res_ = yres_ = pixGetYRes(src);```
I've created small PR #126 that move default value to constant. Tesseract thresholder using ```300```ppi.

**Comment by ws233** [comment]
I see.

**Comment by ws233** [comment]
So it seems that this property has no effect at all :)
Somebody wants a further investigations on this?
Perhaps, it's better to close this?

**Comment by BamX** [comment]
I think it could be closed. Nothing more to discuss about.

**Comment by kevincon** [comment]
I'll close this issue since the question has been answered and we are close to closing #126.
