### ISSUE TITLE
Framework is missing

### ISSUE THREAD

**Issue by gustafnilklint** [gali8/Tesseract-OCR-iOS#128]
For those (like myself) that for different reasons cannot use/don't want to use cocoapods I have been relying on the manual installation of the project. Critical to this installation is the actual .framwork which seems to be removed in one of the later commits.
I know that I could add the framework-project as a build dependency, but I would prefer not to.

Can we have it back please =)

**Comment by ws233** [comment]
@gustafnilklint, that's a bad practice to store binaries in the repository. Binaries significantly increase the size of the repo with every next commit we do. That's why we decided to remove it.
I strongly recommend you to use framework-project or cocoapods.

**Comment by kevincon** [comment]
How about a compromise? @ws233 what if we:

1. Add the framework to the .gitignore file so it won't ever be included in the repo
2. Put back the TesseractOCRAggregate target so that users like @gustafnilklint could build the .framework file themselves for their project

What do you think?

**Comment by ws233** [comment]
Sure. I don't mind compromises :)
But, It's exactly the same as using framework-project, isn't it? There is no need to put back TesseractOCRAggregate target as I see now.
It's possible to compile TesseractOCR target and get the .framework, which could be inserted in any project.
@gustafnilklint, could you explain more detailed what you are going to achieve and why the available approach doesn't satisfy your conditions?

**Comment by kevincon** [comment]
@gustafnilklint I think he's right, can't you just copy TesseractOCR.framework into your project after building the TesseractOCR target in Tesseract-OCR-iOS.xcworkspace? That should be exactly the same as what you did for your project before we removed the framework from the repo.

**Comment by gustafnilklint** [comment]
@ws233 I totally agree that it is bad pratice to commit binaries, especially from your point of view since the project certainly has a lot of activity. On the other hand, from my prerspective I will probably stick with my static library for years to come (hopefully). OCR isn't the main feature of my project
My motivation not to use Cocoapods is that it isn't possible within the companys firewall. As the OCR-funtionality is just one small feature in a fairly large application I want the tesseract lib to make the smallest possible footprint in the overall project.

@kevincon,thats exactly what I ended up doing, I manually built the main xcodeproj and revealed the build framework in finder and copied it to my other project. A few more question though, it was a debug-build since i just pressed play in xcode... Will this make a differance? perhaps i should do a release-build and copy the framework built from it? Will it automatically include all variants (arm7, arm7s, and arm64) if I build the framework like this?

You guys really improved the project a lot latelly! Comparing the current master and the previous 3.4-tag that I used earlier makes a lot of difference in my application.
The ultimate solution here is perhaps a simple shell script the I can run locally after I've fetching, that would generate the "Products"-folder for me to integrate

**Comment by kevincon** [comment]
@gustafnilklint Yeah give the release build a shot and let me know if it works okay. I tried it myself and it built without errors, so I think it should work for you.

It should include all architecture variants because "Build active architecture only" is set to NO for release builds on the framework target in Xcode.

I believe you can generate the framework file using xctool from the command line. I'll look into this tonight to see if I can write a command that gives you the framework file.

**Comment by kevincon** [comment]
@gustafnilklint try this out:

First install xctool if you don't already have it, using homebrew:
```
brew update
brew install xctool
```

Then `cd` to the directory where the Tesseract-OCR-iOS repo is.

Finally, run this xctool command to build the framework in the root of the repo directory. Change `$PWD` if you want to use a different directory to store the resulting framework:

```
xctool -workspace Tesseract-OCR-iOS.xcworkspace -scheme TesseractOCR -configuration Release CONFIGURATION_BUILD_DIR=$PWD
```

**Comment by ws233** [comment]
@gustafnilklint, Thanks for a detailed answer.
You wrote: "As the OCR-funtionality is just one small feature in a fairly large application I want the tesseract lib to make the smallest possible footprint in the overall project."
What about git repo submodule? Its footprint is as small as just a link to this repo in your own repository. I use this approach in my own projects. After you have added a submodule you should proceed the same way as you add a dependency project. But in such case you will have niether a binary nor sources of the tesseract framework in your own repository. That will decrease the footprint significantly. Only the disadvantafe of such approach that the subproject should be rebuilt after every its update. But that happens automatically if you added the OCR as a dependency to your own project. Also it should be mentioned that during rebuilding only the updated parts of the library are being built. So it's not a big issue and doesn't take a lot of time to rebuild only updated files.

Hope, I could explain the approach clear. 

Also @kevincon proposed another approach for you to use the framework.

So, pls, let us know if there is still some questions unanswered or those both approaches are not proper for you.

**Comment by gustafnilklint** [comment]
@ws233, @kevincon  First of all, I am very thankful for your help and I will close the Issue today. I allready use a submodule for the TesseractIOS. Actually I'm working on 3 different apps that share a common git submodule that contain "base funktionality". One of these base funktionalities that is going to be shared is an OCRScannerViewController that needs the Tesseract.framework.
I really like the simplicity of that solution since we allready have a fairly large project/projects. Setting up sub-projects / dependancy project for tessseract adds to the overall complexity / "clutter" of the projects. Thats what I ment with minimum footprint. The .framework file is in my opinion the optimal low-complexity integration.

@kevincon The xctool build works like a charm, unfortunately it only produced a binary with x86 x86_64 architecture. Hopefully I will find a flag to enforce arm7 arm64.

**Comment by ws233** [comment]
ok. fell free to reopen the task if you need more support!

**Comment by kevincon** [comment]
@gustafnilklint Ah interesting, well I hope xctool (and xcodebuild underneath) can build a target for more than one architecture, but it's not clear to me. You might try experimenting with setting multiple values for the `-arch` flag to xctool. Good luck!

**Comment by gustafnilklint** [comment]
Update if anyone else is interested:
xctool -workspace Tesseract-OCR-iOS.xcworkspace -scheme TesseractOCR -configuration Release -sdk iphoneos CONFIGURATION_BUILD_DIR=./Products

Adding the -sdk iphoneos param makes it actually build for arm.

**Comment by iori57** [comment]
@gustafnilklint using the updated command generates a framework that failed to be built with errors such as "Undefined symbols for architecture x86_64" when I select iPhone 6 simulator and "Undefined symbols for architecture i386" when I select iPhone 5 and below simulators.
