### ISSUE TITLE
pixForImage doesn't consider imageOrientation

### ISSUE THREAD

**Issue by ws233** [gali8/Tesseract-OCR-iOS#130]
Steps to reproduce an issue:
1. Rotate any image using 
rotatedImage = [UIImage imageWithCGImage:cgImage scale:_image.scale orientation:orientation]; 
to left or right orientation, so width is changed with height.
2. Set it to the Tesseract with tesseract.image = rotatedImage.
Crash happens. I think the reason is mismatching width and height after rotating. Actually data is not changed after this operation, but width and height do.

@BamX, could you take a look on this and change the code to support any image orientations?

**Comment by BamX** [comment]
Sure, I'll take a look on it tomorrow. Have an idea how to fix it(have some prblems with orientated images in my project).

**Comment by ws233** [comment]
I think a Pix image should be created considerring imageOrientation. I mean, it shouldn't be the exact byte copy of the source image. Instead it should be rotated the same as imageOrientation of the source image.

**Comment by ws233** [comment]
Also I think analyzeLayout function also doesn't work. It returns all 0s for any image I send to it. Do you know how to use this function and what I do wrong?

**Comment by BamX** [comment]
In tests it works fine, isn't it? It return non-zero result for ```deskewAngle```.
