### ISSUE TITLE
Analyser warning - Result of 'malloc' is converted to a pointer of type 'const char *'

### ISSUE THREAD

**Issue by gustafnilklint** [gali8/Tesseract-OCR-iOS#136]
G8Tesseract.mm:166:43: Result of 'malloc' is converted to a pointer of type 'const char *', which is incompatible with sizeof operand type 'int'

const char **configs = (const char **)malloc(sizeof(int) * count);

should probably be changed to:

const char **configs = (const char **)malloc(sizeof(const char*) * count);

**Comment by ws233** [comment]
It seems you're right. But I don't have this warning.
Could you propose more details how I can reproduce this? Which framework and xcode version do you use, which target?

**Comment by ws233** [comment]
Ah. I see. That's an analizer warning.
I'll fix this.
Thank a lot for your contribution, @gustafnilklint!

**Comment by ws233** [comment]
There is a PR with the changes you siggests #137.
