### ISSUE TITLE
Swift tesseract only recognizing gibberish

### ISSUE THREAD

**Issue by DJLectr0** [gali8/Tesseract-OCR-iOS#149]
I use this code to recognize an Image taken by the camera and modified with some filters:
```swift
var tesseract:Tesseract = Tesseract(language: "deu")
tesseract.delegate = self;
tesseract.setVariableValue("01234567890", forKey: "tessedit_char_whitelist");
tesseract.rect = CGRectMake(20, 20, 100, 150);
tesseract.image = theImage;
tesseract.recognize();

NSLog("%@", tesseract.recognizedText);
```
This only recognizes gibberish:
32
3
T5
m
L
CD
U3
8
F
Q
E

When I apply the filters outside the ios app and then use the picture it recognizes correctly.

Images:
Filters withing iOS app
![processedimage](https://cloud.githubusercontent.com/assets/5339762/6234841/1d76853e-b6de-11e4-8b4b-1f4e35de90d0.png)

externally applied:
![some](https://cloud.githubusercontent.com/assets/5339762/6234859/3e4edee6-b6de-11e4-9036-b37c90b8fdf0.png)

As you can see the one within is even clearer yet it does not get recognized.

Note: Without filters it also only recognizes gibberish

**Comment by kevincon** [comment]
What "filters" are you using on the image (both inside and outside the app)?

Have you tried rotating the filtered image within the iOS app to the correct orientation? I don't think Tesseract will perform well on text that is rotated like that.

**Comment by DJLectr0** [comment]
Sorry I posted to the wrong issue. The orientation problem is solved, but now everything gets repeated.
Hallo Tesseract wie geht es dir? Hallo Tesseract wie geht

**Comment by kevincon** [comment]
Can you provide me with more info that I might be able to use to reproduce this issue so I can help you?

**Comment by DJLectr0** [comment]
Weird it seems to work now
