### ISSUE TITLE
G8 prefixed classes

### ISSUE THREAD

**Issue by hzorr** [gali8/Tesseract-OCR-iOS#156]
Hi,
I have installed the Tesseract-OCR-iOS using CocoaPods as described in installation manual is a swift existing project,
But I can't see any G8 prefixed classes that are used in the example
provided on next page, My app works without G8 prefixed classes, 
so what I'm doing wrong

**Comment by gali8** [comment]
Look at https://github.com/gali8/Tesseract-OCR-iOS/issues/141
