### ISSUE TITLE
Speed Expectations?

### ISSUE THREAD

**Issue by johndyer** [gali8/Tesseract-OCR-iOS#157]
Thanks so much for this library. It let me build a concept app super quickly. And I'm excited for the changes in 4.0.0 when it's done.

My only concern is that it takes anywhere from 10-30 seconds to process an entire page of text from an average book. Is this about what you're seeing too? Are there ways to optimize the speed? When I use something like CamScanner it only takes about a second, so I'm wondering if the library is just faster or if they are optimizing the image before sending to the OCR engine.

Sorry for the off-topic question! Again, thanks for all your work....

**Comment by kevincon** [comment]
I think the 10-30 seconds you're experiencing is about right if you're giving Tesseract a high-resolution full page of text, e.g. from a scanner or the iPhone's camera. I think preprocessing the image will give you much faster results. Check out our wiki page on preprocessing images for Tesseract: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results In particular, I think using the ```GPUImageAdaptiveThresholdFilter``` from the GPUImage library will help improve your recognition speed.

**Comment by johndyer** [comment]
Thanks for the recommendations and tips. I'm not sure I'm seeing a lot of improvement with just GPUImageAdaptiveThresholdFilter, but the GPUImage library is great and gives me some good options.

Thanks again for all your hard work!

**Comment by kevincon** [comment]
No problem, feel free to reopen the issue if you would like some more help to try to improve your recognition speed. You can include the image you're trying to recognize on and I can try to think of some other methods for improving the speed.
