### ISSUE TITLE
Need to refactor initializers

### ISSUE THREAD

**Issue by kevincon** [gali8/Tesseract-OCR-iOS#170]
From the discussion in #158, we've decided that we need to refactor the initializers in the following way:

Remove `copyFilesFromResources` from the designated initializer and refactor the code so that the copying of the "tessdata" folder in the app bundle occurs if a folder (any location, "Caches" or otherwise) is specified. If the developer does not have a "tessdata" folder in the app bundle, the code should recognize that case and not try to copy anything from the app bundle to the specified folder, but it should still initialize Tesseract to use the specified folder as the parent of the "tessdata" folder. In that case, it will be the responsibility of the developer to programmatically create the "tessdata" folder in the specified location.

**Comment by ws233** [comment]
Any updates on this?
