### ISSUE TITLE
A single character is not supported？

### ISSUE THREAD

**Issue by hnzlk2014** [gali8/Tesseract-OCR-iOS#174]
Can't analyse layout. Make sure 'osd.traineddata' available in 'tessdata'.
Empty page!!
Empty page!!
![image](https://cloud.githubusercontent.com/assets/6149516/7467667/40187cbc-f330-11e4-80aa-ffdccd4c54b0.png)
![image](https://cloud.githubusercontent.com/assets/6149516/7467670/4d7a87a6-f330-11e4-93bf-f983852173c3.png)

**Comment by ws233** [comment]
Could you provide your code and any tesseract output, if exists, so we could investigate this issue deeply?

**Comment by gali8** [comment]
Have you seen the tessedit_pageseg_mode (kG8ParamTesseditPagesegMode) parameter?
https://github.com/gali8/Tesseract-OCR-iOS/blob/master/TesseractOCR/G8TesseractParameters.m 
http://www.sk-spell.sk.cx/tesseract-ocr-parameters-in-302-version

**Comment by hnzlk2014** [comment]
I use the demo project，Not output. Or set some parameters?

**Comment by ws233** [comment]
I meant console output of tesseract.

**Comment by hnzlk2014** [comment]
![image](https://cloud.githubusercontent.com/assets/6149516/7508094/93c2068a-f4ac-11e4-9cab-7fcbdee4e1a6.png)
![image](https://cloud.githubusercontent.com/assets/6149516/7508103/be54a9c0-f4ac-11e4-98af-5e62bafa8131.png)

**Comment by Jan-M-B** [comment]
Hi,

I get the same error (Can't analyse layout. Make sure 'osd.traineddata' available in 'tessdata'.) when i try to set PageSegmentationMode to PageSegmentationModeAuto, any help?

**Comment by kevincon** [comment]
@Jan-M-B which language are you trying to use? Can you post your code?

**Comment by hovkaren** [comment]
I have same error. My code

        G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"nep"];
        operation.tesseract.engineMode = G8OCREngineModeTesseractOnly;
        operation.tesseract.pageSegmentationMode = G8PageSegmentationModeAuto;

        operation.delegate = (id)self;
        operation.tesseract.image = bwImage;
        [operationQueue addOperation:operation];
        
        operation.recognitionCompleteBlock = ^(G8Tesseract *tesseract) {
            // Fetch the recognized text
            NSString *recognizedText = tesseract.recognizedText;

         };

Can help me.
