### ISSUE TITLE
Xcode 6.3 Warning: [G8RecognitionOperation completionBlock] deprecated property

### ISSUE THREAD

**Issue by yoiang** [gali8/Tesseract-OCR-iOS#175]
Xcode 6.3 warns about overriding the property and that it will still be available.

--verbose
/Users/ian/Documents/Socratic/Socratic/Pods/TesseractOCRiOS/TesseractOCR/G8RecognitionOperation.h:62:25: Auto property synthesis will not synthesize property 'completionBlock'; it will be implemented by its superclass, use @dynamic to acknowledge intention

**Comment by yoiang** [comment]
Looking through the code is this so that consumers of the library do not use `completionBlock` directly and instead use `recognitionCompleteBlock`? Why does `recognitionCompleteBlock` exist in leu of `completionBlock`?

**Comment by ws233** [comment]
as I remember completionBlock is a super property. And it was redeclared in the child class as well. A bit later it had become deprecated. So the way to solve an issue is simply remove its declaration from the child class, I guess.
