### ISSUE TITLE
Tessearct is not recognising the text.

### ISSUE THREAD

**Issue by nikitasatnalika** [gali8/Tesseract-OCR-iOS#179]
i had been following this answer on github https://github.com/gali8/Tesseract-OCR-iOS/issues/153

I followed the lines of code mentioned there but unfortunately its not working for me....I would be grateful if you help me.

my codes are quite similar to the one mentioned though am sending my code and image

G8Tesseract *tesseract = [[G8Tesseract alloc] initWithLanguage:@"eng"];
    tesseract.delegate = self;
    tesseract.image = [[UIImage imageNamed:@"text image.jpg"] g8_blackAndWhite];
    tesseract.rect = CGRectMake(20, 20, 100, 100);
//    [tesseract setImage:[UIImage imageNamed:@"textImg.jpg"]];
    [tesseract recognize];
    NSLog(@"Text %@", [tesseract recognizedText]);
    
//    TxtView.text = tesseract.recognizedText ;

The error I receive is

Error opening data file /Users/moumitadas/Library/Developer/CoreSimulator/Devices/22800DC7-151F-4FCD-A4D0-0037129C8DC0/data/Containers/Bundle/Application/F04EF35F-C3E3-4F21-934E-58C957F95503/pagephones.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

![text image](https://cloud.githubusercontent.com/assets/12556199/7766130/c5a1ee58-0083-11e5-87ce-94d144974b28.jpg)

**Comment by gali8** [comment]
https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation => Importing the tessdata folder

**Comment by nikitasatnalika** [comment]
i have imported the tessdata folder still giving the error. but i dont have the folder icon blue.

**Comment by gali8** [comment]
"Note how the tessdata folder has a blue icon, indicating it was imported as a referenced folder instead of a symbolic group."

When you drag&drop the folder, select "SYMBOLIC GROUP" instead of "referenced folder".

**Comment by nikitasatnalika** [comment]
Thank you..it worked :)

**Comment by roblav96** [comment]
@gali8 
> When you drag&drop the folder, select "SYMBOLIC GROUP" instead of "referenced folder".

But in the wiki:
> NOTE: This library currently requires the tessdata folder to be linked as a referenced folder instead of a symbolic group
> https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation#importing-the-tessdata-folder

Which is correct with most recent cocoapod?

**Comment by roblav96** [comment]
# edit
the one in the wiki is correct. just got it working :D

**Comment by Ramani1994** [comment]
in image using style font image so not detect image to text so image normal font style then apply OCR !
