### ISSUE TITLE
I am getting error building it for distribution 

### ISSUE THREAD

**Issue by gbmgee** [gali8/Tesseract-OCR-iOS#182]
Undefined symbols for architecture arm64:
  "_UIGetScreenImage", referenced from:
      ___25-[AppDelegate handleCall]_block_invoke in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when i run it in iPhone 4 its working fine and i am trying to build for the distribution profile i am getting this error.

i am using the version 4.0.0
Help me regarding this...
Thanks in advance....

**Comment by BamX** [comment]
I don't think that this problem related to Tesseract lib. 
Look at this: http://stackoverflow.com/questions/21640875/is-uigetscreenimage-function-removed-in-ios7

**Comment by kevincon** [comment]
@gbmgee did @BamX's suggestion help you? If so, can you close this issue?

**Comment by ws233** [comment]
@kevincon, it seems not related to tesseract. Let's close this.
@gbmgee, let us know if you still has some issues related to tesseract.
