### ISSUE TITLE
Typo: G8OrientationPareRight => G8OrientationPageRight

### ISSUE THREAD

**Issue by vivekseth** [gali8/Tesseract-OCR-iOS#183]
https://github.com/gali8/Tesseract-OCR-iOS/blob/331afd99f9950367bcb0aa2b4ea29a4c9b3ff5e3/TesseractOCR/G8Constants.h#L137

**Comment by kevincon** [comment]
Nice catch! Can you send us a pull request to fix it so you get the credit?

**Comment by vivekseth** [comment]
Thanks, here you go https://github.com/gali8/Tesseract-OCR-iOS/pull/184 :)

**Comment by kevincon** [comment]
Thanks!
