### ISSUE TITLE
link error with pod install :" pod 'TesseractOCRiOS', '4.0.0'" 

### ISSUE THREAD

**Issue by tuluigi** [gali8/Tesseract-OCR-iOS#188]
i install the class use " pod 'TesseractOCRiOS', '4.0.0"; when i build my project on my iphone6  ,it has errors: 
![1ca01804-a6db-11e4-950c-b5017da24e93](https://cloud.githubusercontent.com/assets/5189595/8399567/96fe6ad0-1e43-11e5-8c99-f11e012433ef.png); this error is architure error; i think may be this is the class's bug. any suggestions  @kevincon ?

**Comment by tuluigi** [comment]
Later, I try to use another method: i install the class with TesseractOCR.framework; but when i build my project ,it has other errors; this is may be the c++ link library error;

**Comment by tuluigi** [comment]
Later, I try to use another method: i install the class with TesseractOCR.framework; but when i build my project ,it has other errors; this is may be the c++ link library error;  
  
![qq20150629-1 2x](https://cloud.githubusercontent.com/assets/5189595/8399630/b6ba115c-1e44-11e5-9cd1-d7733bf413e1.png)
can @kevincon  give me some advice?

**Comment by kevincon** [comment]
I can't tell what the problem is from your snippets? Would you be willing to email me your Xcode project so I can try to debug it myself? If so, email it to me at kcon AT stanford DOT edu.

**Comment by tuluigi** [comment]
hi 
   i have fix this bug, this is my cocospod's problem ; thank you very much @kevincon .
