### ISSUE TITLE
Fix coveralls integration with GitHub

### ISSUE THREAD

**Issue by kevincon** [gali8/Tesseract-OCR-iOS#194]
@gali8, Coveralls no longer comments on new pull requests to report code coverage changes for this repo. Can you check the settings at https://coveralls.io/r/gali8/Tesseract-OCR-iOS? I can't see the settings since I'm not the repo owner.

This related GitHub issue shows that there may just be a checkbox that needs to be checked on the Coveralls settings page: https://github.com/lemurheavy/coveralls-public/issues/93

**Comment by gali8** [comment]
Try now

**Comment by ws233** [comment]
@gali8, That's just from [coverals.io] (https://coveralls.io/builds/2966202/source?filename=TesseractOCR%2FG8RecognitionOperation.m):

> Source Not Available
> The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

**Comment by gali8** [comment]
Please try again, it works for me.

**Comment by ws233** [comment]
Now it works for me too.
Thx!

**Comment by ws233** [comment]
@gali8, Coveralls no longer finishes it's tasks.
Could you take a look at the reasons an try to fix them?

**Comment by ws233** [comment]
@gali8, could you take a look at the issue?
There is a 3rd party PR waiting for aproval,
but I cannot aprove it, since there is no feedback from coveralls.

**Comment by gali8** [comment]
Done!
