### ISSUE TITLE
signal SIGABRT at G8Tesseract.mm (returnCode = _tesseract->Recognize(_monitor);)

### ISSUE THREAD

**Issue by soso2247** [gali8/Tesseract-OCR-iOS#197]
hi

I installed tesseract-OCR 4.0.0 to my Xcode 6(iOS8) using cocoa pods.
and i have some problem with recognizing text
signal SIGABRT error occurred when the app runs `[tesseract recognize];` .

heres code that i used to reorganize text.

`    G8Tesseract* tesseract = [[G8Tesseract alloc] initWithLanguage:@"eng"];
    
    tesseract.charWhitelist = @"0123456789";

    tesseract.image = [notprocessed g8_blackAndWhite];
    
    [tesseract recognize];
    
    [self.textView setText:[tesseract recognizedText]];
    
    NSLog(@"%@", [tesseract recognizedText]);`

i do not have lot of knowledge about these kind of things.
but is that because of my code or some bugs?

**Comment by kevincon** [comment]
Can you post the image you've loaded into the variable `notprocessed`? Can you also show the code that initializes `notprocessed`?

**Comment by soso2247** [comment]
image loaded into `notprocessed` is taken with AVfoundation camera
and this error will also happens with any kinds of image.

code that initializes `notprocessed`:

`UIImage *notprocessed = self.imageView.image;`

**Comment by ws233** [comment]
@soso2247, try your snippet without g8_blackAndWhite. Just send the original image to the tesseract.

**Comment by kevincon** [comment]
@soso2247: And if @ws233's suggestion doesn't work, can you upload your Xcode project to a place like Dropbox or something and share a link with us (or email it to me at kcon AT stanford DOT edu) so we can help you diagnose this error further by looking at the code ourselves?

**Comment by soso2247** [comment]
@ws233 and @kevincon thanks that worked for me. but i want "black&white" feature for this app so any other ways to use black&white?

**Comment by kevincon** [comment]
@soso2247 Can you try to save one of the images that doesn't work with `g8_blackAndWhite` and share it with us? We should try to fix the problem with the `g8_blackAndWhite` function if we can.

But to answer your question, you can also try `g8_grayScale` (it's a little different but maybe it will still help improve recognition), or you can follow some of the guides in our Wiki for alternative methods of preprocessing images: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results

**Comment by soso2247** [comment]
`"Can you try to save one of the images that doesn't work with g8_blackAndWhite and share it with us?"`
Actually this issue happened with any kinds of image but this is one of the example.
(maybe another framework that i installed,"GPUImage" might be the cause of this issue)
<img width="420" alt="test1" src="https://cloud.githubusercontent.com/assets/10205156/8642366/2dc89768-295e-11e5-94c2-b91674bccc77.png">
![img_scn](https://cloud.githubusercontent.com/assets/10205156/8642425/e040d0fe-295e-11e5-8d3d-15497cbf7823.jpeg)

`But to answer your question, you can also try g8_grayScale`
that one worked.
thank you very much.

**Comment by kevincon** [comment]
I was able to throw the image you attached into the Template Framework Project and Tesseract recognized on it successfully, so I think you're right that maybe it was one of your other libraries that was causing the failure.

You can try creating a fresh new project without any additional libraries besides the 4.0.0 CocoaPod for Tesseract and see if you still have issues. If you do, feel free to reopen this issue but include the complete code you're using so we can help you further. I'm going to close this issue now.
