### ISSUE TITLE
Why is G8TesseractDelegate a NSObject?

### ISSUE THREAD

**Issue by iori57** [gali8/Tesseract-OCR-iOS#198]
I wish to use progressImageRecognitionForTesseract callback but the requirement for the delegate to be a NSObject seems weird to me. Isn't it easier to remove this requirement?

I created a class that manages tesseract operations but the class itself is not UIViewController, so making it one just so that it can be used as a G8TesseractDelegate seems strange.

**Comment by kevincon** [comment]
@ws233, you originally created the delegate (https://github.com/gali8/Tesseract-OCR-iOS/commit/6623f0af832897a180a108e6976f7566a680de0b); what do you think?

**Comment by ws233** [comment]
@iori57, can you show a code snippet, which illustrates your efforts?
So far I do not understand why conforming to NSObject makes difficulties for you.

**Comment by iori57** [comment]
Actually it is not a problem now that I've made my manager class (that handles all tesseract operations) a NSObject and it works wonderfully. Just a bit weird that my manager class is a NSObject while it isn't using any of NSObject functions nor behaviours.

Cheers!

**Comment by ws233** [comment]
@iori57, as I remember Apple suggests to inherit any class from one of the available root objects. Otherwise it becomes root object itself.
Anyway, if it's not an issue any more, would you mind colsing the issue?

**Comment by iori57** [comment]
Will close the issue now. Thanks!
