### ISSUE TITLE
numbers not properly recognised

### ISSUE THREAD

**Issue by Swiftology** [gali8/Tesseract-OCR-iOS#200]
Tesseract works fine (especially for word recognition) till I try to test it on a string of 14 or more digits. The result is inconsistent, getting only a few numbers right.
I used the code below:

                    var tesseract:G8Tesseract = G8Tesseract(language:"eng")
                    tesseract.engineMode = .TesseractCubeCombined
                    tesseract.pageSegmentationMode = .Auto
                    tesseract.maximumRecognitionTime = 60.0
                    tesseract.image = newImage.g8_blackAndWhite()
                    tesseract.recognize()
                    let scannedText = tesseract.recognizedText

I am mainly using Calibri font. Could this be the reason?

**Comment by kevincon** [comment]
Unfortunately Tesseract alone is often not sufficient to consistently achieve high recognition accuracy. You can try some of the tips in our wiki: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results. In particular, try using GPUImage to preprocess the image before you give it to Tesseract.

**Comment by ws233** [comment]
@Swiftology, Tesseract doesn't support cube mode anymore.
pls, refer to https://github.com/gali8/Tesseract-OCR-iOS/issues/140
and https://github.com/tesseract-ocr/tesseract/issues/40 for details.
Try default mode instead.

**Comment by Swiftology** [comment]
@kevincon I tried using GPUImage preprocessing but the results seem to be no better.

**Comment by Swiftology** [comment]
@ws233, I tried the default mode but the results are still the same, no improvements.

**Comment by ws233** [comment]
Your next step is training tesseract specifically to your font/fonts. Pls, refer to the documentation for more details.

**Comment by AndreaDiFrancia** [comment]
Is it possible to recognize only the numbers?
