### ISSUE TITLE
library not found for -lTesseractOCRiOS

### ISSUE THREAD

**Issue by hxzjpp** [gali8/Tesseract-OCR-iOS#204]
I just start to use tesseract ocr, and I encounter such problem:
ld: library not found for -lTesseractOCRiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I did follow the install steps. And I have tried some ways such as add library path, but it still did not work. 
And I wonder what is wrong.
Thanks!

d /Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Products/Debug-iphoneos/TakeoutAssistant.app/TakeoutAssistant normal arm64
    cd /Users/Jing/Documents/iOS_Jing_Project/TakeoutAssistant
    export IPHONEOS_DEPLOYMENT_TARGET=8.3
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Products/Debug-iphoneos -L/Users/Jing/Documents/iOS_Jing_Project/TakeoutAssistant/Pods/TesseractOCRiOS/TesseractOCR/lib -F/Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Products/Debug-iphoneos -F/Users/Jing/Documents/iOS_Jing_Project/TakeoutAssistant -filelist /Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Intermediates/TakeoutAssistant.build/Debug-iphoneos/TakeoutAssistant.build/Objects-normal/arm64/TakeoutAssistant.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.3 -dead_strip -lstdc++ -ObjC -weak_library /usr/lib/libstdc++.6.0.9.dylib -lTesseractOCRiOS -llept -lstdc++ -ltesseract_all -framework Foundation -framework UIKit -fobjc-arc -fobjc-link-runtime -framework TesseractOCR -llept -ltesseract_all -framework CoreFoundation -lstdc++.6.0.9 -framework CoreData -lz -framework UIKit -framework CoreGraphics -framework Foundation -framework CoreImage -lPods-TakeoutAssistant -Xlinker -dependency_info -Xlinker /Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Intermediates/TakeoutAssistant.build/Debug-iphoneos/TakeoutAssistant.build/Objects-normal/arm64/TakeoutAssistant_dependency_info.dat -o /Users/Jing/Library/Developer/Xcode/DerivedData/TakeoutAssistant-cxbwrylzppkknueoxfsstncgqchm/Build/Products/Debug-iphoneos/TakeoutAssistant.app/TakeoutAssistant

ld: library not found for -lTesseractOCRiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by marteiro** [comment]
Having the same problem here. Did you figured it out?

Thanks

**Comment by Darkoon** [comment]
Anyone done something about it? Just got this problem too.
