### ISSUE TITLE
Unable to set writing direction and text line order

### ISSUE THREAD

**Issue by iori57** [gali8/Tesseract-OCR-iOS#206]
Inside G8Constants.h there were G8WritingDirection and G8TextLineOrder so I assume that we can change this setting in tesseract. However after I initialized tesseract and try to set writing direction, it gives the error:
"Cannot assign to writingDirection in tesseract" 

Is it read only? Is there another way to set it?

Thanks!

**Comment by ws233** [comment]
@iori57, pls, refer to the [API docs] (http://cocoadocs.org/docsets/TesseractOCRiOS/4.0.0/Classes/G8Tesseract.html#//api/name/writingDirection).

**Comment by iori57** [comment]
Sorry if it is a stupid question.. so does it mean that it is read only and it will be automatically detected and does not need to be configured manually?

**Comment by ws233** [comment]
Yes, it how it's been developed.
