### ISSUE TITLE
Extract Rotated/Tilted Text from Scanned Image

### ISSUE THREAD

**Issue by mervindsouza** [gali8/Tesseract-OCR-iOS#207]
I am currently planning to develop an desktop OCR application using the tesseract OCR engine and fairly I have minimal idea about it.

The task I am facing is extraction of rotated text (any angle) from a scanned image. Kindly find the link : http://1drv.ms/1OS8elW which has the sample PDF document that I need to OCR. The sample contains a blue sticker on it and I need your guidance on extracting the text (printed text) from it.

As you can see the orientation is not stable and i would be really grateful if you could suggest a manner in which i could extract the text.

One method suggested was "to use image processing to identify its location, extract if from the background document it, square it up, and drop the blue background."

How do I implement this?

**Comment by kevincon** [comment]
This isn't really a question about this Tesseract iOS library, but I wanted to start by saying that the upstream Tesseract library has this to say about scanning rotated text (see https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality):

> The quality of Tesseract's line segmentation reduces significantly if a page is too skewed, which severely impacts the quality of the OCR. To address this rotating the page image so that the text lines are horizontal.

The grammar at the end there is bad, but I believe they are saying that it's on you as a developer to give Tesseract horizontal text that has been corrected for any rotation.

To that end, I agree with the suggestion you mentioned about using computer vision to identify its location, extract it from the image, correct its rotation, and drop the blue background. 

Helping with the implementation of these tasks is out of scope for this forum, but the library you'll want to use to perform these tasks is almost definitely OpenCV, and OpenCV has a forum where you can ask for help: http://answers.opencv.org/questions/

In addition to asking for help on the OpenCV forum, you can also just try searching Google for blog posts and articles where people solved similar problems and try to adapt their code for your purposes. Here are a few links I found that you could start with:

http://felix.abecassis.me/2011/10/opencv-rotation-deskewing/
https://gist.github.com/endolith/334196bac1cac45a4893#
http://www.danvk.org/2015/01/07/finding-blocks-of-text-in-an-image-using-python-opencv-and-numpy.html
http://docs.opencv.org/master/d3/db4/tutorial_py_watershed.html
http://opencv-srf.blogspot.com/2010/09/object-detection-using-color-seperation.html
