### ISSUE TITLE
choose chi_sim.traineddata will crash

### ISSUE THREAD

**Issue by xiaoxingan** [gali8/Tesseract-OCR-iOS#208]
I don't know if chi_sim.traineddata is too big(40+M) , can you deal this problem

**Comment by ws233** [comment]
Which device do you use? It seems that 40+M is not a big deal for any Apple device.
What error messages do you get? Can you show a code snipet you try?

**Comment by iori57** [comment]
I just tested chi_sim on both simulator and actual device without any issues. What's the error message that you get?

**Comment by ws233** [comment]
@xiaoxingan, can you ensure that you don't use Cube mode. It seems that Cube mode is no longer supported. Refer to #140 for more details.

**Comment by ws233** [comment]
@kevincon, let's close this as well.

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203


Cube mode is no longer supported for Chinese ???

**Comment by brave1024** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi_sim+chi_tra"];
operation.tesseract.engineMode = G8OCREngineModeTesseractCubeCombined;

2015-09-04 10:13:15.299 CamClaim[15569:4962459] BSXPCMessage received error for message: Connection interrupted

Using default language params

Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /private/var/mobile/Containers/Bundle/Application/FEF9236E-7977-4038-864C-D220533359C1/CamClaim.app/tessdata/chi_sim.cube.lm

Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object

init_cube_objects(true, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 203


Cube mode is no longer supported for Chinese ???

**Comment by brave1024** [comment]
I know the G8OCREngineModeTesseractCubeCombined mode is the most accurate. If I only need recognize English, this mode is ok. But if I need recognize Chinese, this mode can not be used. Anybody helps?

**Comment by ws233** [comment]
@brave1024, is it still an issue for you?

**Comment by Aaaaaaaron** [comment]
@brave1024 u dont have enough resource for engine "Cube". Modify the engine to tesseract only will fix the problem..  .traineddata file just for tesseract engine

**Comment by huangMingHua** [comment]
__block G8Tesseract * tesseract = [[G8Tesseract alloc]initWithLanguage:@"chi_sim" engineMode:G8OCREngineModeTesseractOnly];
chi_sim can't using G8OCREngineModeTesseractCubeCombined,@xiaoxingan，

**Comment by ws233** [comment]
Closing an issue

**Comment by fb2012** [comment]
G8Tesseract *test=[[G8Tesseract alloc]initWithLanguage:@"eng+chi_sim" engineMode:G8OCREngineModeTesseractOnly];
//    test.engineMode=G8OCREngineModeTesseractOnly;
    test.delegate=self;
    [test setImage:[UIImage imageNamed:@"image_sample.jpg" ]];
    [test setRect:CGRectMake(20, 20, 100, 100)];
    [test recognize];



Error:
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53

 I need recognize Chinese, Anybody helps?

**Comment by dipkasyap** [comment]
Same issue here for Korean language cannot use cubeCombined with Korean, Please any one have resource or link of resource for cubeCombined Korean language  Tesseract 3.03-rc1 ?

**Comment by MarkSenCN** [comment]
@fb2012 i am Chinese......but I also this bug error...so Have you solved the problem?
emmm my engilsh is not good,i hope you can understand.....
