### ISSUE TITLE
What about arabic tessdata?

### ISSUE THREAD

**Issue by Munderkind** [gali8/Tesseract-OCR-iOS#209]
I tried tessdata from:
Google https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-3.02.ara.tar.gz&can=2&q=   3.02 
I receive an error  "tessdata_manager.SeekToStart(TESSDATA_INTTEMP):Error:Assert failed:in file adaptmatch.cpp, line 511"

Git, main tesseract repo https://github.com/tesseract-ocr/tessdata
And I receive the same error.

Other languages work well!

**Comment by ws233** [comment]
If it's a question of the language file consistency you would better publish it to the upstream tesseract repository. You may also create your own language file like it's written [here] (https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3).

**Comment by Munderkind** [comment]
In original project "Template Framework Project" arabic works fine, but in the new project does not work, strange...

**Comment by ws233** [comment]
Can you show me your code snippet and the project structure with the tessdata folder in it? (is it blue or yellow?). Could you also provide the whole output of Tesseract from the console?

**Comment by Munderkind** [comment]
Error and tessdata folder: https://www.dropbox.com/s/egplhia77sgpfhw/Edited1.png?dl=0
Log 1: https://www.dropbox.com/s/u76ai73npi5gbem/Edited.png?dl=0
Log 2: https://www.dropbox.com/s/nc1pn7eadxvha53/Edited3.png?dl=0
Code snippet: https://www.dropbox.com/s/29kqq04puc5lz5u/snippet.png?dl=0

**Comment by Munderkind** [comment]
Error and tessdata folder 
![edited1](https://cloud.githubusercontent.com/assets/13694545/9166536/6e1a0dd4-3f5b-11e5-8628-7ffc7e9c6046.png)

Log 1 
![edited](https://cloud.githubusercontent.com/assets/13694545/9166592/8d16f85a-3f5b-11e5-9bf0-56ab10f17422.png)

Log 2 
![edited3](https://cloud.githubusercontent.com/assets/13694545/9166669/b55c696c-3f5b-11e5-9e33-746340f2f944.png)

Code snippet 
![snippet](https://cloud.githubusercontent.com/assets/13694545/9166716/d5beb7a0-3f5b-11e5-80d5-0e0881d91aab.png)

**Comment by Munderkind** [comment]
I found a solution.
![ffffffffffuuuu](https://cloud.githubusercontent.com/assets/13694545/9173758/e87305da-3f84-11e5-817d-4e50c7ff4f81.png)

After changes everything works fine!

**Comment by ws233** [comment]
@Munderkind, so the reason of the crach is in G8OCREngineModeCubeOnly, isn't it?
Does arabic language normally work in Tesseract only mode? If so, pls, refer to #140. It seems that Cube is dead and no longer supported. So I'll change the ticket title to mention arabic language in it as well.

**Comment by ws233** [comment]
@Munderkind, could you also close the ticket if there are no more questions regarding the topic?

**Comment by Munderkind** [comment]
@ws233 Arabic language normally work only in G8OCREngineModeCubeOnly.
In G8OCREngineModeTesseractOnly, G8OCREngineModeTesseractCubeCombined crash with errors.

**Comment by rmtheis** [comment]
FYI, I see the same behavior running Tesseract on Android: https://github.com/rmtheis/tess-two/issues/12

**Comment by mikesalari** [comment]
Isn't working!

**Comment by yaman91** [comment]
@Munderkind Thank you so much, you just saved my day!

**Comment by banuharshavardhan** [comment]
@Munderkind neither `cubeOnly` nor `tesseractCubeCombined` working for me. Can you help me.

**Comment by banuharshavardhan** [comment]
Crash --->

<img width="1280" alt="Screenshot" src="https://user-images.githubusercontent.com/31875244/87398539-a11c9e00-c5d3-11ea-8099-82f3a4162c4d.png">

Code --->

<img width="978" alt="Screenshot 2020-07-14 at 1 13 40 PM" src="https://user-images.githubusercontent.com/31875244/87398683-dfb25880-c5d3-11ea-9f9f-3e4f353024b6.png">

`tessdata` folder --->

<img width="303" alt="Screenshot 2020-07-14 at 1 15 04 PM" src="https://user-images.githubusercontent.com/31875244/87398802-0ff9f700-c5d4-11ea-8a18-33d12e851b3b.png">

**Comment by Abdullah-Alashi-LP** [comment]
Hey @Munderkind and @yaman91 @banuharshavardhan 

I'm getting the same error, I tried the following:

version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)
and without cube data

version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)](https://github.com/tesseract-ocr/tessdata/tree/4.00)
and included cube data from there

version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.0.0/ara.traineddata)
and without cube data

version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.00/ara.traineddata)
and included cube data from there

I made sure to set engineMode: .cubeOnly

can you please please guys add an arabic sample code in git hub 🙏🏻

your help is much appreciated
