### ISSUE TITLE
How to recognize several languages at the same time?

### ISSUE THREAD

**Issue by xuekevin** [gali8/Tesseract-OCR-iOS#211]
Now If I want to get chinese,english and digit in the images, how can I achieve that ?
*G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng"];*
thanks！

**Comment by ws233** [comment]
G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng+chi"];
as it's mentioned in [these code snippets] (https://github.com/gali8/Tesseract-OCR-iOS/wiki/Using-Tesseract-OCR-iOS).

**Comment by xuekevin** [comment]
thanks a lot !

**Comment by Deuce9001** [comment]
I have an error in this part which tells me the following:

No visible @interface for 'G8RecognitionOperation' declares the selector 'initWithLanguage:'eng'

I'll really appreciate if you could help me with this.

**Comment by ws233** [comment]
@Deuce9001, that error does definitely say that you've integrated the framework incorrectly.
Pls, check that how you are adding the framework to your project.
Also, pls, refer to the 'Template Framework Project`
