### ISSUE TITLE
Tesseract low accuracy while using Camera

### ISSUE THREAD

**Issue by parvezq** [gali8/Tesseract-OCR-iOS#212]
For an iOS application using Tesseract SDK version 3.03, I have noticed that if I embed the image to be ocrred and pass its black & white version duly scaled to 640 px then Tesseract sdk gives quite a good accuracy for the extracted text.
On the other hand, if i try to capture the same image using camera and use the same code [as for embedded image then Tesseract do not work at all. I have also checked the orientation of the captured image which is set to UIImageOrientationUp.
Can anybody tell why is there such a difference in behaviour of Tesseract SDK?

**Comment by ws233** [comment]
There is similar [issue] (https://github.com/gali8/Tesseract-OCR-iOS/issues/47).
Pls, take a look deeper on that.
It seems that you do not do enough image preprocessing of your large image. It seems that there is a lot of noise, which is eliminated during scaling down phase. Just try to add any simple noise reduction filter. Adaptive Threshold Filter is the best choise.

Pls, close the ticket if there is no more question regarding the Tesseract accuracy.
Thx!

**Comment by parvezq** [comment]
Thanks for the reply!!!


I am being new to "Adaptive Threshold Filter" so can you please shed some light on how we can apply a filter to remove the noise in the image to have a good ocrred output. I have googled about applying filter to images in iOS to reduce noise and come across OpenCV, TEXTCLEANER but so far not able to figure out how to use.


Thanks

Parvez Qureshi


________________________________

**Comment by kevincon** [comment]
@parvezq we provide sample code for using GPUImage's Adaptive Threshold Filter in the wiki: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results#using-gpuimages-adaptive-threshold-filter

**Comment by ws233** [comment]
@kevincon, let's close this.
