### ISSUE TITLE
G8RecognitionOperation, customize tessdata path

### ISSUE THREAD

**Issue by Jan-M-B** [gali8/Tesseract-OCR-iOS#215]
Hi,

is there a way to customize the tessdata path with G8RecognitionOperation, so something like cachesRelatedDataPath for G8Tesseract?

Jan

**Comment by ws233** [comment]
@Jan-M-B, why don't you just create a simple NSOperation with the tesseract initialized as you wish?
I don't think we need G8RecognitionOperation to support. It doesn't add any specific features or usabilities.

**Comment by Jan-M-B** [comment]
Ok, can you give me an example? I am very new with NSOperation. I already tried this:
```objectivec
    NSOperation *operation = [[NSOperation alloc] init];
    operation.completionBlock = ^{
        [Tess recognize];
    };
    NSOperationQueue *Queue = [[NSOperationQueue alloc] init];
    [Queue addOperation:Operation];
```

But I'm not sure if it's right and a good solution ..
