### ISSUE TITLE
Nominate @ws233 to replace me as project maintainer

### ISSUE THREAD

**Issue by kevincon** [gali8/Tesseract-OCR-iOS#217]
I started a new job a few months ago and since then I haven't had much time to review pull requests and  respond to issues for this repo. 

@ws233 has been doing really great work lately to bring the test coverage up to 100%, enable PDF output support, and prepare the project for XCode 7 and iOS 9, so I'd like to nominate him to replace me as the maintainer of this library.

@ws233, what do you think? Would you be interested in taking over? This would unblock you from landing your pull requests since I don't have time to review them anymore.

**Comment by ws233** [comment]
@kevincon, I've oppositely lost my job a month ago or so, that's why I've contributed so much. But I cannot promise I can be so active further. Just let's try.
I hope you won't forget about the repo and will come to contribute and participate as well as before.
Good luck at your new job!

**Comment by ghrom** [comment]
> On 13 Sep 2015, at 07:37, Cyril <notifications@github.com> wrote:
> 
> I've oppositely lost my job a month ago or so
> 
@kevin Good luck and thank you for contributions! I think @ws233 is good choice.

@ws233 I'm sorry to hear that you lost your job. Would you mind contacting me via LinkedIn https://www.linkedin.com/profile/preview?vpa=pub&locale=en_US if you would be interested in helping with http://imtgapp.com <http://imtgapp.com/> project, please? It is iOS/REST/php project which contains [Tesseract-OCR-iOS] but is not open source itself, so a trade deal would be required of course (as we contact via github, we would have to use their rules as a start, I suppose) ;)

Kind regards,
Piotr

**Comment by ws233** [comment]
@ghrom, let's try, but your LinkedIn profile link is broken.

**Comment by ghrom** [comment]
@ws233, imagine how impressed would I be if you managed to contact me via LinkedIn anyway :) Try this one: https://www.linkedin.com/in/piotrfarbiszewski

**Comment by kevincon** [comment]
> @kevincon, I've oppositely lost my job a month ago or so, that's why I've contributed so much. But I cannot promise I can be so active further. Just let's try.
I hope you won't forget about the repo and will come to contribute and participate as well as before.
Good luck at your new job!

Ah I'm really sorry to hear that you lost your job. I hope you find work again very soon.

@gali8, can you replace my collaborator status with @ws233 so he can take over from me?

**Comment by gali8** [comment]
@ws233 you are a collaborator! Enjoy :)

**Comment by gali8** [comment]
@ws233 give me your email, i will add you in cocoapods too.

**Comment by ws233** [comment]
Kvmakankov at gmail dot com 
Thx!

**Comment by ws233** [comment]
@gali8, don't forget about Travis CI and Coveralls as well, pls.

**Comment by gali8** [comment]
@ws233 verify your email address (about CocoaPods) please.
I think that since you are in TravisCI and Coveralls.

**Comment by ws233** [comment]
Thanks to all!
I'm closing the issue and will reopen a new one, if I need some more access or the given one doesn't work.
Let's do productive work! :)
