### ISSUE TITLE
Cocoapods installation of 4.0.0 - Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by Japspre** [gali8/Tesseract-OCR-iOS#218]
When trying to install the 4.0.0 version through cocoapods I get the following error in Terminal:
**[!] Unable to satisfy the following requirements:**

My pod file:

*pod 'Fabric'
pod 'Crashlytics'
pod 'OCMock', '~> 2.2'
pod 'AFNetworking', '~> 2.0'
pod 'MagicalRecord'
pod 'TesseractOCRiOS', '~> 4.0.0'*

When I install TesseractOCRiOS without specifying a version it installs v3.03.

However, starting a new project, setting up cocoapods and adding only **pod 'TesseractOCRiOS', '~> 4.0.0'** to the podfile will install v4.0.0

Any idea what could go wrong?

**Comment by ws233** [comment]
@Japspre, what do you expect and try to achive?

**Comment by Japspre** [comment]
I wonder which other pod is blocking the installation of v4.0.0

And if I could use another version which will still work on iOS 8 & 9.

**Comment by Japspre** [comment]
If I don't specify any version, v3.03 is installing

**Comment by Japspre** [comment]
After updating cocoapods to v0.39.0 I get a more descriptive message:

Specs satisfying the `TesseractOCRiOS (= 4.0.0)` dependency were found, but they required a higher minimum deployment target.

In the example project iOS7 is the deployment target. I have set iOS8 as deployment target but I still get the same message.

What is the minimum deployment target for this pod?

**Comment by Japspre** [comment]
I had to increase the platform specified in the podfile to 8.0 to fix the problem.
