### ISSUE TITLE
iOS 9: g8_blackAndWhite returns complete black image

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [gali8/Tesseract-OCR-iOS#219]
Hi,

I have been porting my app to work on iOS 9 and found a strange bug.
Under iOS 8, calling 'g8_blackAndWhite' method always returned the proper black and white image. I tested the same on iOS 9 with the same image, it returned, blacked out image. Could you please advice a solution?

Device: iPhone 6+
iOS version: 9.0.1
Framework version: 4.0.0

This maybe helpful: on this line
   'CGImageRef cgiimage = [context createCGImage:output fromRect:output.extent];'
It gives this warning/error:
    'need a swizzler so that RGB8 can be read.'

**Comment by ws233** [comment]
@AnnieNinaJoyceV, hi!
`g8_blackAndWhite` is absolete and is no longer supported.
Why don't you use standard tesseract integrated binarizator?
If it doesn't fit your expectations you ahould consider the [following paper] (https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results).

**Comment by AnnieNinaJoyceV** [comment]
Oh! Thank you for the clarification @ws233 
I'll give it a try :+1:

**Comment by ws233** [comment]
I've marked the functions as deprecated.
