### ISSUE TITLE
Building depedencies script issue on Xcode 7.0.1 with 4.0.0

### ISSUE THREAD

**Issue by drshock** [gali8/Tesseract-OCR-iOS#220]
I have never used Tesseract-OCR-iOS before.  

To evaluate Tesseract out I just unzipped release 4.0.0 and installed Xcode 7.0.1 with command line tools.    Since I do not use CocoaPods I followed the README_how_to_compile_libraries and separately brought down leptonica 1.71 and tesseract 3.03 packages and unzipped them into the same 4.0.0 folder as instructed.
 
When at step 3 of the readme, and then running the build_dependencies script as instructed I get:

build_dependencies.sh: line 141: ./configure: No such file or directory

Is there perhaps some extra step or such not updated in the readme for Xcode 7?

**Comment by ws233** [comment]
pls, check the paths. it seems that you put sources in different folders, than `build_dependencies.sh` script expects.

**Comment by drshock** [comment]
The paths were correct, but the issue was in the script itself, as the path has spaces in it.  So, for example, the line:
cd $LEPTON_LIB
should be written with quotes to deal with embedded spaces:
cd "$LEPTON_LIB"
I'll have to go thru it and adapt but its building Leptonica now.

**Comment by drshock** [comment]
Sadly, ending up having to abandon this. The spaces in the path issue is a limitation with autoconf and wasn't worth trying to work around.   I moved this over to a file path without spaces.

While Leptonica built fine once removing the spaces in the path issue, Tesseract itself, with this 4.0.0 zip anyway, has a number of fatal errors under Xcode 7.0.1 and OSX 10.11.  The following repeats for each ARM build type (both armv7 & armv7s but only pasting in for armv7s):

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: specifed architecture type (armv7s) for file (./outdir/arm7s/libltdl.a) does not match its cputype (16777223) and cpusubtype (3) (should be cputype (12) and cpusubtype (11))
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: archive member ./outdir/arm7s/libtesseract_all.a(argz.o) cputype (16777223) and cpusubtype (3) does not match previous archive members cputype (12) and cpusubtype (11) (all members must match)
 
I'm not having any issues building my own family of apps or their related libraries, so there is something amiss here.
 
The only deviation I had from the included readme, since I already had the Xcode 7 command line tools, was the Xcode version of libtool does not include libtoolize.  I have never needed libtoolize before, so I curled down libtool 2.4 and built it just for Tesseract to be happy and left it installed only in the Tesseract folder.  I did not install anything additional than this and what I already had from Apple with Xcode, but the above fatal errors persisted over several tries amid varying folder paths (none with spaces).

If someone has an idea on the fatal errors I'd love to try again.

**Comment by ws233** [comment]
Why do you need to build libs? There are lib binaries inside the repo.

**Comment by drshock** [comment]
Since I started working with Watch I build everything manually now to insure bitcode / slicing support is going to work if I end up needing to use it.

**Comment by ws233** [comment]
There is a [task about bitcode] (https://github.com/gali8/Tesseract-OCR-iOS/issues/185).
I'm merging it right now. So pls wait a bit and try it.

**Comment by ws233** [comment]
So the binaries are updated and merged in the task metnioned above.
Pls, refer it and get a feedback that it what you expect.
I'm closing this issue as a dublicate.
