### ISSUE TITLE
Question: Is the readme up to date on the library versions?

### ISSUE THREAD

**Issue by drshock** [gali8/Tesseract-OCR-iOS#223]
I see the latest Leptonica 1.72 is included, but the latest Tesseract is 3.04 where the readme indicates 3.03-rc1 is what is in the master branch.   Is this correct?   I have the 3.04 for Android and wanted to be sure I am working with the same level I would be incorprating for iOS to compare results and such.

https://github.com/tesseract-ocr/tesseract/releases

**Comment by ws233** [comment]
Yes, it is.
Pls, refer to #214.

**Comment by ws233** [comment]
I'm closing the issue.
@drshock, pls, feel free to reopen it if you think there is something else to discuss or fix here.
