### ISSUE TITLE
g8_blackAndWhite marked as deprecated, but still shown in the example code

### ISSUE THREAD

**Issue by drshock** [gali8/Tesseract-OCR-iOS#225]
I noticed this was deprecated today.  Since I just got started working with the framework a couple of days ago, it seems then that the Template Framework Project G8ViewController.m should be amended for showing how to use the framework alternatively no?

// Preprocess the image so Tesseract's recognition will be more accurate
    UIImage *bwImage = [image g8_blackAndWhite];

**Comment by ws233** [comment]
An example of binarization is [here] (https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results).
But you are right. The Template Framework Project should be changed to avoid using those depricated functions. I'll do it soon.

**Comment by ws233** [comment]
I've removed all g8_blackAndWhite function calls from the example.
@drshock, thanks for you participation!
