### ISSUE TITLE
ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

### ISSUE THREAD

**Issue by AngeloGiurano** [gali8/Tesseract-OCR-iOS#233]
ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is still happening, tried to disable bitcode but I can't build anyways.

Using XCode 7.1

**Comment by mweibel** [comment]
:+1: have the same issue
