### ISSUE TITLE
The recognizedText is not string when I user Swift

### ISSUE THREAD

**Issue by mars-rover** [gali8/Tesseract-OCR-iOS#236]
It's my code 
    func recognizeImage(image: UIImage) {
        let tesseract:G8Tesseract = G8Tesseract(language:"eng")
        tesseract.delegate = self
        tesseract.charWhitelist = "01234567890"
        tesseract.image = image
        tesseract.recognize()
        print("recognized text:\(tesseract.recognizedText.utf8)")
    }
but the output is not character, it is numbers like:
recognized text:55 8199 919 993 20128 4 9
9 193 3624291919919
9299995299 0
9 09935953 9 29 99
99999
695190109161 8 69 99
9149991659 69 99
994999 9 9 99
191690096 993396 8 69 99
099659 9 69 99
91139
19199991139929 0
how can I fix it?

**Comment by ws233** [comment]
What do you expect?
Why do you think those aren't characters? They are. It's a string.
You've specified `charWhitelist` with only digets.
That means Tesseract will try to recognize only those specified characters and only them.
Pls, refer to the wiki.

**Comment by mars-rover** [comment]
Thank you very much! It works, I am new to Tesseract-OCR-iOS, Thank you for your efforts!

**Comment by ws233** [comment]
Do you have any other issues related to this?
If don't, pls, close the ticket. Thx!
