### ISSUE TITLE
progressImageRecognitionForTesseract

### ISSUE THREAD

**Issue by mars-rover** [gali8/Tesseract-OCR-iOS#239]
I can't got the 100% progress when I using the delegate method progressImageRecognitionForTesseract (Swift)

**Comment by ws233** [comment]
That's an expected behaviour.
As I remeber recognition progress value starts from 30% upto 90%.
Could find a quick prove in the upstream Tesseract wiki for you, but you can do it yourself.

**Comment by mars-rover** [comment]
Alright, thanks a lot!

**Comment by Isuru-Nanayakkara** [comment]
Yes, it starts from 30 and ended in 93 for me. Is this the same for all situations? Or does it change based on the image that's scanned or any other factors?

**Comment by ws233** [comment]
@Isuru-Nanayakkara, pls, refer to rhe upstream Tesseract.

**Comment by Isuru-Nanayakkara** [comment]
@ws233 Hi, I'm sorry but what do you mean by upstream Tesseract? I'm not quite familiar with that.

**Comment by ws233** [comment]
https://github.com/tesseract-ocr
