### ISSUE TITLE
Unable to run Template Framework Project

### ISSUE THREAD

**Issue by yosukesugishita** [gali8/Tesseract-OCR-iOS#240]
I'm having a trouble running Template Framework Project.

I cloned this repo, installed CocoaPods and followed the instruction to add Podfile to my directory.

![image](https://cloud.githubusercontent.com/assets/1811651/11763548/45da7712-a0c4-11e5-84b5-5b09d6b7039d.png)

I then ran
> pod install
which seemed to have worked.

However, I get the following error when I try to run the app in Xcode:
> ld: framework not found TesseractOCR
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://cloud.githubusercontent.com/assets/1811651/11763551/6d608e16-a0c4-11e5-99b0-265a3c3b9761.png)

How can I fix this?

Thanks so much in advance!!

**Comment by Deuce9001** [comment]
You need to add the TesseractOCR.framework manually, as you can see those files are in red. So, erase the files in red and add the TesseractOCR.framework manually.

I upload the framework you need to add in this comment for you.

[TesseractOCR.framework.zip](https://github.com/gali8/Tesseract-OCR-iOS/files/67546/TesseractOCR.framework.zip)

**Comment by ws233** [comment]
@yosukesugishita, why do you add `Template Framework Project` to your own project?
It's not a framework! It's a template, which shows the way to use the `TesseractOCR-iOS` framework.
Pls, use cocoapods correctly to integrate the pod into your project. Also you don't need to clone the repo, if you use cocoapods.

**Comment by quchangle** [comment]
I'm troubled by a error, when I use CoreImage Framework and Tesseract.  I use CIDetector to recognize QR code，It returns nil for it need arm64，but my tesseract don't support arm64.how can i  solve the problem.
Thanks so much in advance!!

**Comment by ws233** [comment]
@quchangle, which `TesseractOCR-iOS` version do you use?
It supports the `arm64` architecture in current version.

**Comment by quchangle** [comment]
@ws233 do you have current version of TesseractOCR-iOS which supports the arm64? could you help me? I really need this framework for my program.In our country ,the development of technology is not very mature and there are not so many resources.I can't find the resources of TesseractOCR -iOS.I really need your help. thank u very  very  very  very  very  very  very  very  very  very  very  very  very  very much!
  Thanks so much in advance !!

**Comment by ws233** [comment]
@quchangle, just clone this repo.

**Comment by quchangle** [comment]
oh~ i find! so great you are. I love you!!!hahhhhhh
