### ISSUE TITLE
ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

### ISSUE THREAD

**Issue by pbrewczynski** [gali8/Tesseract-OCR-iOS#244]
I've tried to compile with Tesseract-OCR-iOS (stable release) added via Cocoapods.

Is something wrong with bitcode on Tesseract or any dependency? 

Of course disabling bitcode fixes problem.

When I remove "-weak_library" from: 

"OTHER_LDFLAGS = $(inherited) -ObjC -weak_library /usr/lib/libstdc++.6.0.9.dylib -l"TesseractOCRiOS" -l"lept" -l"stdc++" -l"tesseract_all" -framework "Foundation" -framework "UIKit""

in Pods.debug.xconfig

I get:

d: '/Users/pbrewczynski/Dev/[[NAME OF PROJECT]]/Pods/TesseractOCRiOS/TesseractOCR/lib/libtesseract_all.a(strngs.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

I also noted that in 9.2  "libz.dylib" is renamed to  "libz.tbd"

Paul

**Comment by ws233** [comment]
Pls, try master version.
Closing as a [dublication] (https://github.com/gali8/Tesseract-OCR-iOS/issues/233).
