### ISSUE TITLE
Controlling stream to Tesseract

### ISSUE THREAD

**Issue by Katafalkas** [gali8/Tesseract-OCR-iOS#245]
I want to recognize text in stream of images I capture in real time via camera. When I start sending images to Tesseract it breaks. I thought to controll it with `if tesseract.progress == 100` but that did not help. after recognizing 5 image or so - it breaks.

It usually breaks on `G8Tesseract.mm:699` if i keep trying to recognize text from my testing image.
![screen shot 2016-01-02 at 16 55 45](https://cloud.githubusercontent.com/assets/1636440/12074822/aa3f006a-b172-11e5-9b7b-7559658690f4.png)

Or it breaks on `G8Tesseract.mm:773` if I try passing it image from stream data.
```
func captureOutput(captureOutput: AVCaptureOutput!, didOutputSampleBuffer sampleBuffer: CMSampleBuffer!, fromConnection connection: AVCaptureConnection!) {
        let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)
        let image = CIImage(CVPixelBuffer: pixelBuffer!)
        self.tesseract.image = UIImage(CIImage: image)
        tesseract.recognize()
```
![screen shot 2016-01-02 at 16 58 40](https://cloud.githubusercontent.com/assets/1636440/12074824/bd354fe4-b172-11e5-9f74-5c291db63138.png)

The second case might not be exactly relevant to the stream control part of the question.

I am using `TesseractOCRiOS (4.0.0)`

**Comment by ws233** [comment]
Don't you mind showing your code related to Tesseract?

**Comment by Katafalkas** [comment]
This is my full view controller. Its messy, but thats a concept test project .. :D
https://gist.github.com/Katafalkas/5804f7d3a8aeda9450e3

**Comment by ws233** [comment]
Try recreating tesseract on every recognition effort.

**Comment by ws233** [comment]
@Katafalkas, I've modified `Template Framework Project` as follows and it works.
So it seems there is no issue in `TesseractOCRiOS` regarding recognizing multi images.
It's probably in your code. Pls, double check that you send correct image frames to the Tesseract.
The second crach you mentioned seems very likely like a `nil` input image.
Also if you find any issue related to the `TesseractOCRiOS`, feel free to reopen the task.
So far I'm closing the issue.

    -(void)recognizeImageWithTesseract:(UIImage *)image
    {
    // Animate a progress activity indicator
    [self.activityIndicator startAnimating];

    // Create a new `G8RecognitionOperation` to perform the OCR asynchronously
    // It is assumed that there is a .traineddata file for the language pack
    // you want Tesseract to use in the "tessdata" folder in the root of the
    // project AND that the "tessdata" folder is a referenced folder and NOT
    // a symbolic group in your project
    G8Tesseract *tesseract = [[G8Tesseract alloc] initWithLanguage:@"eng"];

    // Use the original Tesseract engine mode in performing the recognition
    // (see G8Constants.h) for other engine mode options
    tesseract.engineMode = G8OCREngineModeTesseractOnly;
    
    // Let Tesseract automatically segment the page into blocks of text
    // based on its analysis (see G8Constants.h) for other page segmentation
    // mode options
    tesseract.pageSegmentationMode = G8PageSegmentationModeAutoOnly;
    
    // Optionally limit the time Tesseract should spend performing the
    // recognition
    //operation.tesseract.maximumRecognitionTime = 1.0;
    
    // Set the delegate for the recognition to be this class
    // (see `progressImageRecognitionForTesseract` and
    // `shouldCancelImageRecognitionForTesseract` methods below)
    tesseract.delegate = self;

    // Optionally limit Tesseract's recognition to the following whitelist
    // and blacklist of characters
    //operation.tesseract.charWhitelist = @"01234";
    //operation.tesseract.charBlacklist = @"56789";
    
    for (int i = 0; i<100; i++) {
        // Set the image on which Tesseract should perform recognition
        tesseract.image = image;
        [tesseract recognize];
        NSLog(@"%@", tesseract.recognizedText);
    }

    // Optionally limit the region in the image on which Tesseract should
    // perform recognition to a rectangle
    //operation.tesseract.rect = CGRectMake(20, 20, 100, 100);
    #if 0
    // Specify the function block that should be executed when Tesseract
    // finishes performing recognition on the image
    operation.recognitionCompleteBlock = ^(G8Tesseract *tesseract) {
        // Fetch the recognized text
        NSString *recognizedText = tesseract.recognizedText;

        NSLog(@"%@", recognizedText);

        // Remove the animated progress activity indicator
        [self.activityIndicator stopAnimating];

        // Spawn an alert with the recognized text
        UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"OCR Result"
                                                        message:recognizedText
                                                       delegate:nil
                                              cancelButtonTitle:@"OK"
                                              otherButtonTitles:nil];
        [alert show];
    };
    
    // Display the image to be recognized in the view
    self.imageToRecognize.image = operation.tesseract.thresholdedImage;

    // Finally, add the recognition operation to the queue
    [self.operationQueue addOperation:operation];
    #endif
    }
