### ISSUE TITLE
charWhitelist still picks up letters and other characters

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [gali8/Tesseract-OCR-iOS#253]
I want to scan the *Order No* from the below image.

![dscf0167](https://cloud.githubusercontent.com/assets/2551877/13377821/0542958c-de12-11e5-94d8-3237a013632a.JPG)

Here's my code for that.

```swift
let scaledImage = photosManager.scaleImage(leadImage, maxDimension: 640)

let tesseract = G8Tesseract(language: "eng")
tesseract.language = "eng"
tesseract.charWhitelist = "0123456789"
tesseract.engineMode = .TesseractCubeCombined
tesseract.pageSegmentationMode = .Auto
tesseract.maximumRecognitionTime = 60
tesseract.image = scaledImage.g8_blackAndWhite()
tesseract.recognize()

if !tesseract.recognizedText.isBlank {
    let whitespacesStrippedString = tesseract.recognizedText.removeWhitespace().stripWhiteSpaces()
    let stringComponents = whitespacesStrippedString.componentsSeparatedByCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet())
    stringComponents.forEach { component in
        if component.lowercaseString.containsString("order") {
            let orderNumber = component.componentsSeparatedByString(":").last
            OrderNumber = orderNumber
            print("Scanned Order Number: \(OrderNumber)")
        }
    }
}
```

The scanned result I'm getting is this - **274377i.**

It contains an **i** and a period even though I have specified the character white list for only numbers. I changed the `engineMode` to `.TesseractOnly` and nothing gets scanned then.

Any idea why this is happening?

**Comment by ws233** [comment]
`charWhitelist` specifies the charachters that should have a larger choosing rate, it doesn't garantee guarantee that all the rest characters are skipped.
pls, use 'charBlacklist` specifying all the rest symbols you would like to be banned.
I'm closing an issue. Let me know, if you have further questions.
