### ISSUE TITLE
Linker error: ld: -weak_library and -bitcode_bundle cannot be used together

### ISSUE THREAD

**Issue by navarionek** [gali8/Tesseract-OCR-iOS#255]
Hello, I've followed the steps in the Installation page but I can't get this library to work.

I've added the library in the pod file:

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Przypominajka2' do
pod 'TesseractOCRiOS', '4.0.0'
end

```
This is the error I get after building:
![screen shot 2016-03-04 at 16 08 25](https://cloud.githubusercontent.com/assets/16014572/13530770/5a300b5a-e223-11e5-8c43-dc90f03a4437.png)

I've set Enable Bitcode to false in both pods and my project, but the error still shows.
Any help would be appreciated, thanks.

**Comment by ws233** [comment]
pls, use the most recent version of the lib.
the version from the master

**Comment by CptJolly** [comment]
I have the same issue and i use the latest version

**Comment by kwerle** [comment]
You have [other] pods that are configured with bitcode_enabled = yes.  At least I did.  Look at every single pod you have and check that flag.  Configuring your project (and ignoring the pods project) is not enough.

**Comment by EddyVerbruggen** [comment]
Just FYI - This lib is the only Pod I use so to disable bitcode I did:

```
pod 'TesseractOCRiOS', <your spec>

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by ws233** [comment]
Closing an issue.
