### ISSUE TITLE
Is the app Google Translate built using this project?

### ISSUE THREAD

**Issue by sunshineo** [gali8/Tesseract-OCR-iOS#258]
That app is amazing!
Anyone from that team here?
Is that built using Tesseract or it talks to some powerful stuff on Google's backend?

Also anyone know any open source library that help you select text/section of image by swipe your finger on it like the Google Translate app?

Thank you in advance!

**Comment by sunshineo** [comment]
Someone was looking for the same thing
http://stackoverflow.com/questions/12704201/highlight-text-on-image-similar-to-google-translate-app
But answer my question please:
http://stackoverflow.com/questions/36183030/any-open-source-library-allow-swipe-on-image-to-highlight-select-sections-text

**Comment by ws233** [comment]
We are not the authors of Google Translate app.
So we cannot answer your question.
Purhaps, the developers who are responsible for the Tesseract core can answer it.
So, pls, post your question in the [upstream tesseract repository](https://github.com/tesseract-ocr/tesseract).
I'm closing the issue now. Let me know if you have any other questions. Thanks!

**Comment by sunshineo** [comment]
Thank you @ws233
