### ISSUE TITLE
Tesseract variable crashes app when called within an extension

### ISSUE THREAD

**Issue by agates4** [gali8/Tesseract-OCR-iOS#264]
When called within a keyboard extension, the following code results in a crash:

```
   ` let tesseract:G8Tesseract = G8Tesseract(language:"eng")`
```

The error:

```
   ` viewServiceDidTerminateWithError:: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 " (null)" UserInfo={Message=Service Connection Interrupted}
```

`

If it matters, I do have keyboard full access enabled.

**Comment by ws233** [comment]
@agates4 Have you linked you extention app with the Tesseract iOS wrapper as it mentioned in the installation doc?

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
