### ISSUE TITLE
Can not make in Mac OS X

### ISSUE THREAD

**Issue by Tom-Shen** [gali8/Tesseract-OCR-iOS#265]
I tried `make` in this directory:
/path/to/Tesseract-OCR-iOS-master/TesseractOCR
It gives me this error:
```
tomandjerry:TesseractOCR yifengshen$ make
git submodule init
fatal: Not a git repository (or any of the parent directories): .git
make: *** [/Users/yifengshen/Desktop/Tesseract-OCR-iOS-master/TesseractOCR/tesseract-ocr/autogen.sh] Error 128
```

**Comment by ws233** [comment]
It seems that you haven't push the repositiory from the git, it seems that you have just copied it.
By the way, why do you need to compile TesseractOCR-iOS Frameqork from the scratch?
There is already a prebuilt binary of the framework included for you in the repository sources

**Comment by ws233** [comment]
Ah! I see. For the MacOS-X.
MacOS isn't currently supported.
There is a corresponding ticket #27, so I'm closing the issue.
You may also refer to the docs in the [upstream repo](https://github.com/tesseract-ocr/tesseract). There should be a usefull info explaining how to build it for MacOS.
