### ISSUE TITLE
Auto Crop image

### ISSUE THREAD

**Issue by edvenkat** [gali8/Tesseract-OCR-iOS#270]
Hai friends......
We take the photo (with A4 Sheet and some background) using camera....... We need to crop the A4 Sheet only (Without background) is possible...? please advice........

**Comment by ws233** [comment]
It's not possible with Tesseract, as far as I know.
I'm closing an issue.
Feel free to reopen it, if you think it's related with Tesseract-OCR-iOS wrapper.
