### ISSUE TITLE
Xcode ios Tesseract linker error

### ISSUE THREAD

**Issue by vkoushik** [gali8/Tesseract-OCR-iOS#273]
Hi,

I perfofmed all the installation instructions starting from pod install, added libz.dylib in the link with libraries,added tessdata and at last added the line -lstdc++ in other linker flags.Next, i ran the code and received the error in the screenshot
![screen shot 2016-06-30 at 7 25 30 pm](https://cloud.githubusercontent.com/assets/18536586/16499550/efef501a-3ef8-11e6-8d4d-44585ebc165c.png)

Can some one please help with me with this issue?

Thank you

**Comment by mingjiameng** [comment]
I have the same problem. 
<img width="752" alt="2016-08-16 10 45 08" src="https://cloud.githubusercontent.com/assets/7894962/17703105/20eeb4ba-6403-11e6-9ed9-502827fd7a7a.png">

**Comment by xander94** [comment]
I had this same problem. Try going to your pods project and then selecting the TesseractOCRiOS target. Go into build settings and search for 'Enable Bitcode'. Set that to 'No'. Then clean and build.
<img width="811" alt="screen shot 2016-09-28 at 11 14 31" src="https://cloud.githubusercontent.com/assets/5012745/18909827/118bdfb2-856d-11e6-9170-439977ac8751.png">

**Comment by ws233** [comment]
@vkoushik is it still an issue for you?
I'm closing it, but feel fre to reopen it, if you need more help.

**Comment by vkoushik** [comment]
No, it is not. Thank you
