### ISSUE TITLE
Forking and refactoring for compatibility with macOS

### ISSUE THREAD

**Issue by dylanjt3** [gali8/Tesseract-OCR-iOS#274]
I'm thinking about forking this repository and refactoring some parts to make it compatible with Mac for a personal project.

It is clearly stated in README that OS X is not supported; other than dependencies on other iOS-exclusive pods (e.g. libtiff), are there any other major breaking points to be aware of?

**Comment by ws233** [comment]
The differences in Frameworks between iOS and MacOS?
There is a [ticket](https://github.com/gali8/Tesseract-OCR-iOS/issues/27) about porting. Pls, refer to it for more details.
Also why don't you apply your changes in the way that the Tesseract-OCR-iOS becomes a universal Tesseract-OCR-ObjC? :) I mean, why don't you push your changes to this repository so every developer can access the result of your porting efforts and perhaps help you with this?
I'm going to close this ticket as a duplicate.
Let's continue in that ticket.
