### ISSUE TITLE
How can I create a new Language traineddata?

### ISSUE THREAD

**Issue by vbonluk** [gali8/Tesseract-OCR-iOS#276]
When I add new *.traineddata file in tessdata and run project,I got this error:

read_params_file: parameter not found: allow_blob_division

I try to deal with this problem:

combine_tessdata -e *.traineddata *.config

but I got this error in command:

zsh: command not found: combine_tessdata

I had been cd to training folder which had a combine_tessdata.cpp file 

Please Help~

**Comment by ws233** [comment]
It seems that you `*.traineddat` is broken.
Anyway, we are not responsible for the Upstream Tesseract.
We are writting an iOS wrapper here only.
So for any question related to the Tesseract core, pls, refer the [Upstream repo](https://github.com/tesseract-ocr).
