### ISSUE TITLE
Upgrade to Tesseract 3.04?

### ISSUE THREAD

**Issue by rpbrokaw** [gali8/Tesseract-OCR-iOS#277]
Are there any plans to upgrade Tesseract-OCR-iOS to wrap the current version of Tesseract, v3.04?

Has any analysis been done to evaluate that upgrade?
Any sense of the effort?
Any sense of the potential upside in speed? accuracy?

**Comment by ws233** [comment]
pls, refer to #214.
I'm closing an issue as a duplicate.
Feel free to reopen it if you think it's a different issue and you can provide more details about it.
Thx!

**Comment by rpbrokaw** [comment]
Thanks -- sorry for the dupe
