### ISSUE TITLE
ENABLE_BITCODE issue

### ISSUE THREAD

**Issue by matrosovDev** [gali8/Tesseract-OCR-iOS#279]
I've tried to build my project, but I got that issue:

ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've tried to set ENABLE_BITCODE to NO, but it does not help.

**Comment by wkretzsch** [comment]
same here.

**Comment by wkretzsch** [comment]
This seems to be a duplicate of this comment https://github.com/gali8/Tesseract-OCR-iOS/issues/244

**Comment by matrosovDev** [comment]
If I remember I fixed it with specifying:
config.build_settings['ENABLE_BITCODE'] = 'NO'

in my pod file

**Comment by tedhogan** [comment]
Same issue.

**Comment by sealz** [comment]
Thanks @tedhogan, saved me a lot of googling.

Here's an easier to copy and paste version.
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by 1234Karthick** [comment]
@tedhogan 
It worked, thanks so much.
