### ISSUE TITLE
embedded dylibs/frameworks are only supported on iOS 8.0 and later

### ISSUE THREAD

**Issue by artemisia-absynthium** [gali8/Tesseract-OCR-iOS#281]
Hi, I'm trying to build a project with deployment target 7.0, using Tesseract Master version, but linker fails throwing this error:

> `ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/TesseractOCR.framework/TesseractOCR) for architecture armv7`

On the README it says support from 7.0+ and raising it to 8.0 is not an acceptable solution for me because I only have a 7.1 device to test on at the moment (since I'm using camera I cannot use the simulator).

![Log](https://cloud.githubusercontent.com/assets/7290872/17804095/60021d06-65fa-11e6-9082-e60462d1acd1.png)

**Comment by artemisia-absynthium** [comment]
I found the [solution](http://stackoverflow.com/a/36212682/5219866), it seems like the TesseractOCRiOS target comes out from Cocoapods with default deployment target set to 8.0.

**Comment by sosofr74** [comment]
I have the same issue using 8.0
![capture d ecran 2016-10-18 a 14 56 45](https://cloud.githubusercontent.com/assets/20417063/19478525/377ab74e-9543-11e6-8088-f6fa453326c7.png)
