### ISSUE TITLE
read_params_file: parameter not found: allow_blob_division

### ISSUE THREAD

**Issue by hmilyyjm** [gali8/Tesseract-OCR-iOS#283]
Hi, I use Tesseract-OCR-iOS pass CocoaPods ,while I want to  recognize 'chi_sim' , app crash ,error is  'read_params_file: parameter not found: allow_blob_division', but I use 'eng', It's OK，
some article say I need excute command line 'combine_tessdata -e chi_sim.traineddata chi_sim.config', but I didn't pass the command line installation Tesseract-OCR, Is it necessary?
There are other ways？，if Have ,please tell me.~~~~Omz

**Comment by elenabratanova** [comment]
@hmilyyjm 
If you want a quick temp solution you can simply take older versions of traneddata that are compatible:
https://github.com/tesseract-ocr/tessdata/tree/4d64457aacbc781a94d6aefc125765c3949c8827

I heard newer ones are better at recognizing things, but older work too and are also compatible with this lib.

**Comment by softwarefaith** [comment]
@elenabratanova I use  older versions of traneddata,but app still crash.   
error: read_params_file: parameter not found: allow_blob_division.

Can you describe the solution in detail?

**Comment by ws233** [comment]
hi @elenabratanova! how are you doing in Tango? ;-)

**Comment by ws233** [comment]
@hmilyyjm I'm closing an issue, since TesseractOCR-iOS is not a Tesseract core itself.
Here we are responsible for iOS wrapper only.
If you have any questions about lang files or the core, pls, contact the [upstream Tesseract](https://github.com/tesseract-ocr) for that.
Thanks!

**Comment by sulaimansust** [comment]
Hi. I am having similar problem for japanese traindedata. It's work fine for english but while i initialize Tessarect with "jpn", this create the same problem. Is there any effective solution for this case ???
