### ISSUE TITLE
linker command fail error

### ISSUE THREAD

**Issue by uchitapal** [gali8/Tesseract-OCR-iOS#286]
ld: library not found for -ltesseract_all
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by uchitapal** [comment]
please solve this problem as soon as possible...

**Comment by uchitapal** [comment]
i am using ios 9.3. i follow exact step given by GitHub to create Tesseract simple project but i spend one day to solve this issue....

**Comment by elenabratanova** [comment]
@uchitapal I had similar problem, but it was because I was running the project and not the workspace in XCode (after you run pod install it will generate a workspace and you should open it for stuff to work correctly)

**Comment by ws233** [comment]
@uchitapal also, pls. use the most recent version from the HEAD of the master.
Is it still an issue for you?
I'm closing it, but feel free to reopen it if you have any questions

**Comment by uchitapal** [comment]
thank you @elenabratanova for solution it work for me
