### ISSUE TITLE
Can‘t compile on device

### ISSUE THREAD

**Issue by mm-manu** [gali8/Tesseract-OCR-iOS#293]
Hi,
I have problems compiling my Swift project using Tesseract-OCR-iOS.

My environment:
XCode 7.3.1
Swift 2.2
Target iOS version: 9.3
Tesseract-OCR-iOS version 4.0.0 from CocoaPods

I did the following:

- Created a new project in XCode (project name: OCR)
- pod init
- Changed the Podfile to this:
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
target 'OCR' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TesseractOCRiOS', '4.0.0'
end
```
- pod install (success)
- Opened OCR.xcworkspace in XCode
- Added libz.tbd to "Link Binary with Libraries"
![image](https://cloud.githubusercontent.com/assets/2395900/19650762/b6f5909a-9a0a-11e6-9e68-c6310ae8c524.png)
- Changed Enable Bitcode to NO
- Added tessdata folder (appears as blue folder as it should)
- Created a Bridging Header file
![bildschirmfoto 2016-10-24 um 17 01 01](https://cloud.githubusercontent.com/assets/2395900/19651010/8e61cd0a-9a0b-11e6-8064-b869e3c8d1ca.png)
- In my ViewController, I imported TesseractOCR, however, there is a red line drawn through TesseractOCR
![bildschirmfoto 2016-10-24 um 17 02 46](https://cloud.githubusercontent.com/assets/2395900/19651099/e104ac6c-9a0b-11e6-8e32-9099a429cfbf.png)
- However, the import gives no error.
- I can run the app in the simulator without problems, however when I want to run it on a real device, I get the following error:
![bildschirmfoto 2016-10-24 um 17 07 06](https://cloud.githubusercontent.com/assets/2395900/19651233/53a332f2-9a0c-11e6-85a3-dbb02d915a62.png)

It says that I shoudl disable bitcode, however, changing bitcode to no does not make any difference.

Can someone help please?

**Comment by sdost** [comment]
You need to also disable bitcode on the Pod target. The easiest way to do that is to add this to your Podfile: 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by mm-manu** [comment]
Thanks, I also found this solution. It works!
The issue be closed.
