### ISSUE TITLE
Build failed ENABLE_BITCODE = YES ?

### ISSUE THREAD

**Issue by altinselimi** [gali8/Tesseract-OCR-iOS#294]
So I set Enable_bitcode to No, in my Build Settings, but still receive this error :

`ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Then went ahead and added this line to my podfile: 

`config.build_settings['ENABLE_BITCODE'] = 'NO'` 

But still the same error. I also added the "Other linker flags" and added the libz.tbd to Link Binaries with Libraries section in Build Phases, as prescribed in the installation guide, but still no luck.

**Comment by mmbabaev** [comment]
Make sure that you set enable bitcode yes for tesseract target, not your own project.

 Also, you can use this fork by @spronin :
https://github.com/gali8/Tesseract-OCR-iOS/pull/291

He recompiles libraries, so tesseract doesn't fail compile with this error.

**Comment by carlosdelamora** [comment]
@mmbabaev can you be more specific on what you mean to set bitcode yes for tesseract target?

**Comment by mmbabaev** [comment]
@carlosdelamora It's my mistake, I meant set enable bitcode to NO. When I wrote "for tesseract target" I assumed that author set value only for his project, to avoid this error you should set enable bitcode both in your target
![2016-11-07 13 25 45](https://cloud.githubusercontent.com/assets/12600807/20054432/6554fb76-a4f6-11e6-9201-545b0ab3d14e.png)
and TesseractiOS target
![2016-11-07 13 25 52](https://cloud.githubusercontent.com/assets/12600807/20054438/6ad99598-a4f6-11e6-9420-efe113f6933f.png)
