### ISSUE TITLE
TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53

### ISSUE THREAD

**Issue by AdrianBinDC** [gali8/Tesseract-OCR-iOS#300]
I installed via Cocoapods 1.1.1 (latest). I added `pod 'TesseractOCRiOS', '4.0.0'
` to my `Podfile`. I install `eng.traineddata` in the `tessdata` directory (as a reference)

In the compiler, everything works fine as I write the code to start the recognize method, but the moment `tesseract.recognize()` is called, I get the following in the console and the app crashes:

`actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53`

I've tried reinstalling, deintegrating, etc., cleaning, etc. I'm getting the `eng.traineddata` data file from `https://github.com/tesseract-ocr/tessdata`

**Comment by AdrianBinDC** [comment]
Used an older version of `traineddata` found elsewhere. [Details here](http://stackoverflow.com/a/41168236/4475605).

**Comment by MDOBreno** [comment]
> Not sure why this was closed, using old version of traineddata is not a solution, it is just workaround and the accuracy with the old traineddata is not as good as new ones.

That means that either you are not using the newest version of Tesseract, or the new version of _traineddata_ doesn't work.

If you're not in the newest version of Tesseract, update it.
If they released a broken _traineddata_ version, you just have to wait for them to fix it.

Any way, what you can do now is using the old(but functional) version.
