### ISSUE TITLE
Swift 3 crash

### ISSUE THREAD

**Issue by mihailsalari** [gali8/Tesseract-OCR-iOS#308]
I have installed Tesseract 4.0.0 version and the last [eng.traineddata file ](https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata), the error is:
**_actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53_**

How to resolve?

**Comment by pattersongp** [comment]
+1 I am having the same issue

**Comment by agusmao** [comment]
Try using the 3.04 version of the trained data
[https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.traineddata]
