### ISSUE TITLE
Does This Library Run on iOS 6?

### ISSUE THREAD

**Issue by Stunner** [gali8/Tesseract-OCR-iOS#31]
Wondering if this library runs for iOS 6.

**Comment by wkretzsch** [comment]
Hey, @Stunner can you still get the 4.0.0 release of this library to work on ios 6?

**Comment by Stunner** [comment]
Not sure. Last I touched this was two years ago. Based on the date of my comments on this thread I assume [release 2.22](https://github.com/gali8/Tesseract-OCR-iOS/commit/4034d80277eef38892a486fcac4d5a884aa8ea3c) was what I was looking at.
