### ISSUE TITLE
can not run on my iPhone, but can run on Xcode simulator?

### ISSUE THREAD

**Issue by litt1e-p** [gali8/Tesseract-OCR-iOS#319]
can not run on my iPhone, but can run on Xcode simulator,
error message: 
```
Apple Mach-O Linker (ld) Error Group clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
can anybody help me? thanks.

**Comment by litt1e-p** [comment]
fixed. just set `Enable Bitcode` = `NO`

**Comment by 13409795771** [comment]
666  you solved my problem @litt1e-p

**Comment by litt1e-p** [comment]
@13409795771 🎉

**Comment by 13409795771** [comment]
Can he recognize Chinese? @litt1e-p

**Comment by 13409795771** [comment]
Can it recognize Chinese? @litt1e-p

**Comment by litt1e-p** [comment]
you can generate tessdata with Chinese training, or download tessdata

**Comment by 13409795771** [comment]
I need to recognize the license plate,Because I'm Chinese, the license plate have Chinese and number ,so i need two language,  but This method has only one parameter，  [[G8RecognitionOperation alloc] initWithLanguage:@"eng"];   so what should i do....?!~

**Comment by 13409795771** [comment]
I need to recognize the license plate,Because I'm Chinese, the license plate have Chinese and number ,so i need two language, but This method has only one parameter， [[G8RecognitionOperation alloc] initWithLanguage:@"eng"]; so what should i do....?!~       @litt1e-p

**Comment by litt1e-p** [comment]
```
        G8Tesseract *tesseract = [[G8Tesseract alloc] initWithLanguage:@"eng"];
        tesseract.delegate = self;
        tesseract.charWhitelist = @"0123456789";
        tesseract.image = [self g8_blackAndWhite];
        //    tesseract.rect = CGRectMake(20, 20, 100, 100);
        tesseract.maximumRecognitionTime = 2.0;
        [tesseract recognize];
```
the `eng.traineddata` supports number.  @13409795771
