### ISSUE TITLE
arabic doesn't working  

### ISSUE THREAD

**Issue by ahmedAlmasri** [gali8/Tesseract-OCR-iOS#324]
language : swift 3.1
pod v 1.1.1
esseract-OCR-iOS 4.0.0 

using ara.traineddata   file 
error 
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53

**Comment by keohoangphuong** [comment]
The current version of eng.traineddata linked above on GitHub will not work with the current version of the Tesseract-OCR-iOS.

The installation instructions posted on GitHub work perfectly if you've got the right <language>.traineddata file.

I discovered this after dragging the eng.traineddata from Lyndsey Scott's brilliant Tesseract tutorial on Ray Wenderlich.

This repo contains the eng.traineddata file I needed to get Tesseract working. I'm not sure if that applies to all languages.

**Comment by ahmedAlmasri** [comment]
thank you it's working

**Comment by scubess** [comment]
Hi @ahmedAlmasri , 

I am working on ara.traineddata and it is not working for me. Can you tell me how you made it working please and also did you used cube data to make it working ?

**Comment by Abdullah-Alashi-LP** [comment]
Hey @scubess and @ahmedAlmasri 

I'm getting the same error, I tried the following:

version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)
and without cube data

version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)](https://github.com/tesseract-ocr/tessdata/tree/4.00)
and included cube data from there

version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.0.0/ara.traineddata)
and without cube data

version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.00/ara.traineddata)
and included cube data from there

I made sure to set engineMode: .cubeOnly

your help is much appreciated
