### ISSUE TITLE
xCode 9 `tessdata` folder can't be created in app bundles.

### ISSUE THREAD

**Issue by beeth0ven** [gali8/Tesseract-OCR-iOS#330]
In xCode 9 you can't create folder in app bundles:

![2017-07-07 11 23 55](https://user-images.githubusercontent.com/5554127/27942067-d834c95e-6306-11e7-93e4-9adefcacd796.png)

Which cause the `eng.traineddata` file is not embed in 'tessdata' folder:

![2017-07-07 11 24 33](https://user-images.githubusercontent.com/5554127/27942094-1168b988-6307-11e7-9401-29589fdbc172.png)

Then will get a runtime error:

```
Error opening data file /var/containers/Bundle/Application/592A44F5-F6C2-4E78-BCB7-72602522790D/VisionDemo.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
```

**Comment by gali8** [comment]
Follow the wiki page

**Comment by beeth0ven** [comment]
@gali8 Thanks, Finally I find the solution.

**Comment by FaribaHeidari** [comment]
I have the same problem. I am using xcode 9.2 and tesseract 4. Please share your solution. thank ypu
