### ISSUE TITLE
Could not find the right traineddata

### ISSUE THREAD

**Issue by ryh** [gali8/Tesseract-OCR-iOS#333]
I followed the [WIKI](https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation),   `tessdata` files no longer existed on https://code.google.com but github, I tried using this https://github.com/tesseract-ocr/tessdata/tree/3.04.00
and in iPhone EMU console print "`read_params_file: parameter not found: allow_blob_division`" 
then crash, without Xcode can debug it.
So which version of traineddata we shall use?

**Comment by Rufy86** [comment]
i've had the same problem using jpn.traineddata file. @gali8 can you say us how can we fix it?

**Comment by SilmeLyy** [comment]
+1
