### ISSUE TITLE
Version confusing

### ISSUE THREAD

**Issue by zhouhao27** [gali8/Tesseract-OCR-iOS#334]
I saw you release the version for Tesseract 4.0 already. But it shows Tesseract 3.0.3  in REAEME. What is the current version Tesseract now? Thanks.

I got the following error message when I followed the instruction in "Installation":

```
[!] Error installing TesseractOCRiOS
[!] /usr/bin/git clone https://github.com/gali8/Tesseract-OCR-iOS.git /var/folders/nl/nk7hhvts5ljc_d60dpyyzb440000gn/T/d20170814-70269-gwedb2 --template= --single-branch --depth 1 --branch 4.0.0

Cloning into '/var/folders/nl/nk7hhvts5ljc_d60dpyyzb440000gn/T/d20170814-70269-gwedb2'...
fatal: unable to access 'https://github.com/gali8/Tesseract-OCR-iOS.git/': Empty reply from server
```
Any idea?

**Comment by zhouhao27** [comment]
When I change the platform in Podfile from:

`platform :ios, "9.0"`

to 

`platform :ios, "8.0"`

The problem solved.

**Comment by gali8** [comment]
Great!
