### ISSUE TITLE
Tesseract and CoreML

### ISSUE THREAD

**Issue by Rufy86** [gali8/Tesseract-OCR-iOS#335]
Is it possible to convert tesseract or a component in a CoreML model?

so you can insert the tessdata you want and to use CoreML framework

**Comment by gali8** [comment]
I think is not supported by tesseract.
Anyway is a great idea!!!

Daniele Galiotto | www.nexor.it

Inviato da iPhone

**Comment by Rufy86** [comment]
do you think to try it? I don't know to try it

**Comment by gali8** [comment]
Let me understand coreml :)

Daniele Galiotto | www.nexor.it

Inviato da iPhone

**Comment by saria85** [comment]
Any update on this?
