### ISSUE TITLE
How to config the TESSDATA_PREFIX environment variable?

### ISSUE THREAD

**Issue by jeanboydev** [gali8/Tesseract-OCR-iOS#355]
I want put eng.traineddata in Documents directory, but always print:

> Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.

**Comment by KarenAn** [comment]
It seems that .traineddata must bu put in the directory named 'tessdata'

**Comment by Mondonno** [comment]
It's not working @ZhizhiHu ....
:(

**Comment by marcelogrsp** [comment]
I am with the same issue here, any good?

**Comment by Mondonno** [comment]
I have a lot of errors with the Tessaract :/  And i do not know how to bypass this

**Comment by namicCD** [comment]
don't put your eng.traineddata in a path contains Chinese
it work for me 

> I am with the same issue here, any good?

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
