### ISSUE TITLE
Arabic is not working 

### ISSUE THREAD

**Issue by scubess** [gali8/Tesseract-OCR-iOS#374]
Hi, 
I tried to make it work in ara.traineddata without cube. But it show me error,

`actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53
`
But it is working fine with eng.traineddata. Can someone help me please ?

**Comment by ahbou** [comment]
I just went through this too.
Arabic only works in Cubic mode so you need to include the [trained_data from here ](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-304305)

and [the cubic files from here](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#cube-data-files-for-version-304305)

AND **set the engine mode before init**

`tesseract = G8Tesseract(language: "ara", engineMode: .cubeOnly) `

**Comment by scubess** [comment]
Hi @ahbou ,
i tried it now. I am getting another error, 
`tessdata_manager.SeekToStart(TESSDATA_INTTEMP):Error:Assert failed:in file ../../classify/adaptmatch.cpp, line 511`
And also, i noticed the datafiles and cube files you refered is for v3.04 and seems it won't work with 3.03-rc1 (lower version in iOS) ? Any help please

**Comment by ahbou** [comment]
I'm using the latest Tesseract-OCR-iOS v4.0 with those files and it works.
Make sure you init with engineMode: .cubeOnly

**Comment by scubess** [comment]
Hi @ahbou ,
Just let you know it works and thanks for your help !

**Comment by AhmedElsayedTaha** [comment]
@ahbou  Please I want to use Arabic so I can't find Cubes data and how to use engineMode: .cubeOnly in my code ?in Android

**Comment by AhmedElsayedTaha** [comment]
@ahbou  I can't download cubes file from here , and I can't find them :( :(
https://github.com/tesseract-ocr/tessdata/tree/3.04.00

**Comment by Abdullah-Alashi-LP** [comment]
Hey @scubess and @ahbou 

I'm getting the same error, I tried the following:

1. 
version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)
and without cube data

2. 
version [[5.0.1](https://github.com/gali8/Tesseract-OCR-iOS/tree/5.0.1)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/main/ara.traineddata)](https://github.com/tesseract-ocr/tessdata/tree/4.00)
and included cube data from there

3. 
version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.0.0/ara.traineddata)
and without cube data

4. 
version [[4.0.0](https://github.com/gali8/Tesseract-OCR-iOS/tree/4.0.0)] with [[ara.traineddata](https://github.com/tesseract-ocr/tessdata/blob/4.00/ara.traineddata)
and included cube data from there

I made sure to set engineMode: .cubeOnly

your help is much appreciated

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by jagu070** [comment]
does it work on the tesseract version 5? because im getting error  TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53 this is the error which i get

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by jagu070** [comment]
tessdata_manager.SeekToStart(TESSDATA_INTTEMP):Error:Assert failed:in file ../../classify/adaptmatch.cpp, line 511. how to fix this error
