### ISSUE TITLE
Build Tesseract 4.0 official release (not 4.0.0alpha)

### ISSUE THREAD

**Issue by tehilata** [gali8/Tesseract-OCR-iOS#391]
Hi,
I want to build Tesseract 4.0.0 (not alpha or beta) version from 
https://github.com/tesseract-ocr/tesseract/releases. *without using cocoapods.
Anyones help?
Thanks

**Comment by ZkHaider** [comment]
This should be a good direction: 
`https://github.com/tesseract-ocr/tesseract/blob/449fc8af29835d3f186fdeb9c5c32d95ed43df7f/INSTALL`

**Comment by ZkHaider** [comment]
I went ahead and built it with bitcode if you find that useful: [#398](https://github.com/gali8/Tesseract-OCR-iOS/pull/398)

**Comment by tehilata** [comment]
> This should be a good direction:
> [tesseract-ocr-build instructions](https://github.com/tesseract-ocr/tesseract/blob/449fc8af29835d3f186fdeb9c5c32d95ed43df7f/INSTALL)

Thank you !!!
