### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by KGDeveloper** [gali8/Tesseract-OCR-iOS#396]
Undefined symbols for architecture x86_64:
  "STRING::STRING(STRING const&)", referenced from:
      GenericVector<STRING>::operator+=(GenericVector<STRING> const&) in G8Tesseract.o
      GenericVector<STRING>::operator+=(STRING) in G8Tesseract.o
      GenericVector<STRING>::clear() in G8Tesseract.o
  "_pixCreate", referenced from:
      -[G8Tesseract pixForImage:] in G8Tesseract.o
  "_pixGetDepth", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "_pixSetSpp", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "_pixGetWidth", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "tesseract::TessBaseAPI::SetRectangle(int, int, int, int)", referenced from:
      -[G8Tesseract setEngineRect:] in G8Tesseract.o
  "_pixGetData", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
      -[G8Tesseract pixForImage:] in G8Tesseract.o
  "STRING::~STRING()", referenced from:
      ___27-[G8Tesseract configEngine]_block_invoke in G8Tesseract.o
      -[G8Tesseract variableValueForKey:] in G8Tesseract.o
      GenericVector<STRING>::reserve(int) in G8Tesseract.o
      GenericVector<STRING>::operator+=(GenericVector<STRING> const&) in G8Tesseract.o
      GenericVector<STRING>::operator+=(STRING) in G8Tesseract.o
      GenericVector<STRING>::clear() in G8Tesseract.o
  "tesseract::TessBaseAPI::GetThresholdedImage()", referenced from:
      -[G8Tesseract thresholdedImage] in G8Tesseract.o
  "tesseract::TessResultRenderer::BeginDocument(char const*)", referenced from:
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
  "tesseract::TessBaseAPI::ProcessPage(Pix*, int, char const*, char const*, int, tesseract::TessResultRenderer*)", referenced from:
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
  "_pixGetWpl", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
      -[G8Tesseract pixForImage:] in G8Tesseract.o
  "tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool)", referenced from:
      -[G8Tesseract configEngine] in G8Tesseract.o
  "tesseract::TessResultRenderer::EndDocument()", referenced from:
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
  "tesseract::TessBaseAPI::GetHOCRText(int)", referenced from:
      -[G8Tesseract recognizedHOCRForPageNumber:] in G8Tesseract.o
  "tesseract::TessBaseAPI::GetIterator()", referenced from:
      -[G8Tesseract characterChoices] in G8Tesseract.o
      -[G8Tesseract recognizedHierarchicalBlocksByIteratorLevel:] in G8Tesseract.o
      -[G8Tesseract recognizedBlocksByIteratorLevel:] in G8Tesseract.o
  "_pixConvertTo1", referenced from:
      -[G8Tesseract setEngineImage:] in G8Tesseract.o
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
  "tesseract::TessBaseAPI::Recognize(ETEXT_DESC*)", referenced from:
      -[G8Tesseract recognize] in G8Tesseract.o
  "_pixSetYRes", referenced from:
      -[G8Tesseract pixForImage:] in G8Tesseract.o
  "tesseract::LTRResultIterator::WordFontAttributes(bool*, bool*, bool*, bool*, bool*, bool*, int*, int*) const", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
  "STRING::STRING(char const*)", referenced from:
      ___27-[G8Tesseract configEngine]_block_invoke in G8Tesseract.o
  "tesseract::LTRResultIterator::WordIsFromDictionary() const", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
  "tesseract::ChoiceIterator::Confidence() const", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
      -[G8Tesseract characterChoices] in G8Tesseract.o
  "tesseract::ChoiceIterator::~ChoiceIterator()", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
      -[G8Tesseract characterChoices] in G8Tesseract.o
  "tesseract::TessBaseAPI::Version()", referenced from:
      +[G8Tesseract version] in G8Tesseract.o
  "_pixGetSpp", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "tesseract::LTRResultIterator::Confidence(tesseract::PageIteratorLevel) const", referenced from:
      -[G8Tesseract blockFromIterator:iteratorLevel:] in G8Tesseract.o
  "tesseract::TessBaseAPI::AnalyseLayout()", referenced from:
      -[G8Tesseract analyseLayout] in G8Tesseract.o
  "tesseract::TessBaseAPI::GetUTF8Text()", referenced from:
      -[G8Tesseract recognizedText] in G8Tesseract.o
  "tesseract::TessPDFRenderer::TessPDFRenderer(char const*)", referenced from:
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
  "tesseract::LTRResultIterator::WordIsNumeric() const", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
  "tesseract::TessBaseAPI::TessBaseAPI()", referenced from:
      -[G8Tesseract tesseract] in G8Tesseract.o
  "tesseract::TessBaseAPI::SetImage(Pix const*)", referenced from:
      -[G8Tesseract setEngineImage:] in G8Tesseract.o
  "tesseract::ChoiceIterator::Next()", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
      -[G8Tesseract characterChoices] in G8Tesseract.o
  "_pixDestroy", referenced from:
      -[G8Tesseract setEngineImage:] in G8Tesseract.o
      -[G8Tesseract recognizedPDFForImages:] in G8Tesseract.o
      -[G8Tesseract thresholdedImage] in G8Tesseract.o
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "tesseract::ChoiceIterator::ChoiceIterator(tesseract::LTRResultIterator const&)", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
      -[G8Tesseract characterChoices] in G8Tesseract.o
  "tesseract::ChoiceIterator::GetUTF8Text() const", referenced from:
      -[G8Tesseract hierarchicalBlockFromIterator:iteratorLevel:] in G8Tesseract.o
      -[G8Tesseract characterChoices] in G8Tesseract.o
  "STRING::operator=(STRING const&)", referenced from:
      GenericVector<STRING>::push_back(STRING) in G8Tesseract.o
      GenericVector<STRING>::reserve(int) in G8Tesseract.o
  "tesseract::TessBaseAPI::SetSourceResolution(int)", referenced from:
      -[G8Tesseract setEngineSourceResolution:] in G8Tesseract.o
  "tesseract::TessBaseAPI::GetVariableAsString(char const*, STRING*)", referenced from:
      -[G8Tesseract variableValueForKey:] in G8Tesseract.o
  "_pixUnpackBinary", referenced from:
      -[G8Tesseract thresholdedImage] in G8Tesseract.o
  "STRING::string() const", referenced from:
      -[G8Tesseract variableValueForKey:] in G8Tesseract.o
  "tesseract::PageIterator::Orientation(tesseract::Orientation*, tesseract::WritingDirection*, tesseract::TextlineOrder*, float*) const", referenced from:
      -[G8Tesseract analyseLayout] in G8Tesseract.o
  "tesseract::TessBaseAPI::SetVariable(char const*, char const*)", referenced from:
      -[G8Tesseract setVariableValue:forKey:] in G8Tesseract.o
      ___28-[G8Tesseract loadVariables]_block_invoke in G8Tesseract.o
  "_pixGetHeight", referenced from:
      -[G8Tesseract imageFromPix:] in G8Tesseract.o
  "tesseract::PageIterator::BoundingBox(tesseract::PageIteratorLevel, int*, int*, int*, int*) const", referenced from:
      -[G8Tesseract blockFromIterator:iteratorLevel:] in G8Tesseract.o
  "tesseract::TessBaseAPI::ClearPersistentCache()", referenced from:
      +[G8Tesseract clearCache] in G8Tesseract.o
  "STRING::STRING()", referenced from:
      -[G8Tesseract variableValueForKey:] in G8Tesseract.o
      GenericVector<STRING>::reserve(int) in G8Tesseract.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MindaugasJucius** [comment]
@KGDeveloper link `libc++.tbd` with your project

<img width="902" alt="screen shot 2019-02-03 at 4 44 09 pm" src="https://user-images.githubusercontent.com/17001066/52178099-ef205600-27d2-11e9-86a0-ebe538e302c9.png">

**Comment by KGDeveloper** [comment]
@MindaugasJucius 谢谢
