### ISSUE TITLE
The result is really not good

### ISSUE THREAD

**Issue by iPermanent** [gali8/Tesseract-OCR-iOS#42]
I used the image with texts which is get by office word, but the result is really bad, should I do some other settings for the use like the encoding or something else? And by the way, where is the Chinese tessdata, I need to recongnize the Chinese as well. Thanks for your excellent work.

**Comment by kevincon** [comment]
I've moved the information provided here to the Wiki: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results 

I've also added some more notes about using GPUImage. I'll close this issue, but any other ideas about improving OCR results for Tesseract should be added to the Wiki page.

**Comment by ws233** [comment]
Good job!

Should we explain about skipping the internal thresholding somewhere? or at least mention about this feature on that page?

**Comment by kevincon** [comment]
Yeah I think that'd be good to add. Want to add another section (one "#" in markdown) to explain about it?

**Comment by ws233** [comment]
How can I do this? Do I have a write access to the Wiki?
Wow! I do! :)
Let me try.

**Comment by ws233** [comment]
No. actually I don't. I can only edit the Sidebar content. I cannot find how to edit the wiki pages.

**Comment by kevincon** [comment]
I think you should be able to because @BamX was able to edit one of the Wiki pages and he doesn't have collaborator status. Here's where I see it:

![screen shot 2015-01-06 at 11 12 26 am](https://cloud.githubusercontent.com/assets/817753/5634497/fb29c73a-9594-11e4-87e8-ea2e1751fa56.png)

**Comment by ws233** [comment]
Ah! Thanks a lot for the help.
Seems ok now.
