### ISSUE TITLE
Access _tesseract instance variable

### ISSUE THREAD

**Issue by joaomvfsantos** [gali8/Tesseract-OCR-iOS#52]
Is there a way (by subclassing or by other means) to access the _tesseract instance variable? This would be interesting if we would like to further customize the Tesseract class. Or is there a better way to do this?

**Comment by kevincon** [comment]
@joaomvfsantos, we don't have a good/safe way to provide access to the underlying `tesseract` variable right now.

I'm going to close this issue for now, but if there is specific functionality/customization you'd like to see in the library, please open a new issue so we can discuss adding it for you. Depending on the customization, a subclass-based solution (like you mentioned) may be possible.
