### ISSUE TITLE
how to init tesseract to use tessdata from document path?

### ISSUE THREAD

**Issue by flysofast** [gali8/Tesseract-OCR-iOS#53]
Thanks for your pod, it's saved me a lot of time to compile the library. 
Just one small issue: I'm writing an application that let user decide which language they want to perform OCR on, and then they could download the corresponding .traineddata file. It works well in iOS emulator but on real device, I cannot add files to MainBundle root path (seems like it's a security problem), so I have to store the .traineddata files in document folder, and I couldn't initialize tesseract from this data path (as the method has been dedeprecated). 
Is there anything I can do? Thanks in advance.

**Comment by kevincon** [comment]
This issue is resolved by the new functionality in #113. See the bottom of this page in the Wiki for information about how to use it: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Advanced-Tesseract-Configuration
