### ISSUE TITLE
How to get paragraph wise text?

### ISSUE THREAD

**Issue by Swaroop1231** [gali8/Tesseract-OCR-iOS#54]
Hi, Tesseract API is wonderful and working great.But how it returns paragraph wise text.Suppose take below image as example here I need to get paragraph wise text, I mean I am getting all the messages as single string, so I am unable to differentiate the paragraphs in that string in this scenario. How can I do this?Here doesnt it consider two lines text as single paragraph? Two lines in a same box returning two strings.
 Waiting for your reply.Thanks in advance.

![hi](https://cloud.githubusercontent.com/assets/2819782/4322238/e963101e-3f46-11e4-9630-5f91d91860eb.jpeg)

**Comment by ws233** [comment]
This one also could be closed, I think, since there is a function 
- (NSArray *)confidencesByIteratorLevel:(G8PageIteratorLevel)pageIteratorLevel; 
which returns the blocks of text for the G8PageIteratorLevelParagraph.

**Comment by kevincon** [comment]
I agree. @Swaroop1231, feel free to reopen this issue or start a new one if you have any more questions.
