### ISSUE TITLE
Tesseract can't open trained data

### ISSUE THREAD

**Issue by golergka** [gali8/Tesseract-OCR-iOS#55]
I've created new project with CocoaPods and Tesseract and load the tesseract

```
Error opening data file /var/mobile/Applications/8900B20E-746E-445B-A328-575C94E50CA6/check.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
```

Here's the code:

``` swift
class ViewController: UIViewController, TesseractDelegate {

    var tesseract : Tesseract?

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        tesseract = Tesseract(language: "eng")
        tesseract!.delegate = self
    }
```

Of couse, I indeed have tessdata folder inside my project folder, and there's `eng.traineddata` file there as well,

**Comment by Ithoughts** [comment]
I go through the same error  'Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.'  When I try to change the eng.traineddata to chi_sim.traineddata.What the mistake I have made?

**Comment by ws233** [comment]
@Ithoughts, That means, that tesseract can not see you traineddata files.
So the reasons could be:
1. You put them in a wrong folder. The corret place to put is explained above.
2. You missed some files. There could be more than one file necessary for you language.
3. You chose wrong version of traineddata files. The current tesseract core version is 3.0.x. That means you should try the same version of traineddata files.
Pls, check all the above and let us know if that's fixed your issue.

**Comment by Ithoughts** [comment]
@ws233  I have put them in a right folder and chose the right version of traineddata files.As you concerned,'You missed some files. There could be more than one file necessary for you language.',I wonder what files I have missed,what files are necessary?How to generate the indeed files?Thanks!

**Comment by ws233** [comment]
There is a very detailed page about training tesseract: https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3. But before you jump into this, could you provide your traineddata files, specify the path, where you put them and show a code snippet, which you use to run tesseract?

**Comment by Ithoughts** [comment]
@ws233 I just put the chi_sim.traineddata into the tessdata file,but its recognition is horrible.how can I improve the recognition of Chinese?What can I do ?Please give me a detailed tip,thanks a lot!

**Comment by tarungarg** [comment]
Download eng.traineddata from Google
$ wget https://tesseract-ocr.googlecode.com/files/eng.traineddata.gz

Then just move it into the ../tessdata/

$ gunzip eng.traineddata.gz 
$ sudo mv -v eng.traineddata ../tessdata/

**Comment by FattigerTao** [comment]
@kevincon thank you.

**Comment by nguyenhungvbhp** [comment]
how to  the "tessdata" folder has a blue icon

**Comment by Paul95278** [comment]
@Ithoughts  I have the same problem as you now, have you worked out it,? So, could you give me some advices, thanks!

**Comment by jdawg844** [comment]
how do you move the eng.traineddata to tessdata on mac OS?
