### ISSUE TITLE
[Proposal] Move the documentation to the wiki

### ISSUE THREAD

**Issue by zachberger** [gali8/Tesseract-OCR-iOS#64]
I'd like to propose moving documentation from the README.md to the wiki. The wiki allows information to be organized into discrete pages instead of one huge file, and allows documentation to be community supported. @gali8, if you don't mind this change I'd be willing to put in the work to migrate to the wiki.

**Comment by ws233** [comment]
Home page in Wiki is empty :(
Should we copy some info from readme file there?
And there is only one line about the project in the readme. What is the project? Why is this? How can it help developers? and so on. Perhaps, we could take some info from upstream Tesseract.

What do you also think about asking upstream tesseract holders to add the link to this project to their wiki? Here, for example: https://code.google.com/p/tesseract-ocr/wiki/3rdParty. There are 2 iOS projects already exist, but both are very old and one is a branch of G8 repo, actually, while another has tes 2 core.

**Comment by BamX** [comment]
We also could add reference to this repository on wiki page of Tesseract: [wiki/Tesseract (software)](https://en.wikipedia.org/wiki/Tesseract_(software))

**Comment by ws233** [comment]
I've added a note to wiki: https://en.wikipedia.org/wiki/Tesseract_%28software%29.

**Comment by BamX** [comment]
Well done!

**Comment by kevincon** [comment]
@ws233 cool! 

As for the README, I think it's okay because we link to the relevant parts of the Wiki.

We should definitely add more info to the Wiki homepage. If my other note helps you edit Wiki pages, then feel free to get started on that.

And yeah, maybe when we finish the 4.0.0 release we can ask the upstream guys to add this project to their 3rd party wiki page.

**Comment by ws233** [comment]
I've written some info on Home page and added a topic related to Tesseract integrated thresholder bypassing here: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results
Could you take a look on this and correct my broken English or add something important, what I forgot to mention?

**Comment by ws233** [comment]
And I found that API is not documented at all. There are only methods without any descriptions. Is it a known issue?

**Comment by kevincon** [comment]
It will be automatically updated when we release the cocoa pods update.

**Comment by kevincon** [comment]
Thanks for your additions to the Wiki, @ws233. I improved the wording on them and a few other tweaks; let me know if you think it looks okay.

**Comment by kevincon** [comment]
I think the last Wiki page that needs to be edited before we can close this issue is the Contributing page: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Contributing

I'll find some good information to put in the "How to contribute" space and then close this issue. I'll work on this tonight.

**Comment by kevincon** [comment]
I finally added instructions for the "How to contribute" section of the Wiki, so I'll go ahead and close this issue now.
