### ISSUE TITLE
Init Only Variables

### ISSUE THREAD

**Issue by stuartthomas25** [gali8/Tesseract-OCR-iOS#68]
Tesseract OCR iOS is unable to set "Init Only" variables like user_words_suffix and load_system_dawg  (see https://code.google.com/p/tesseract-ocr/wiki/ControlParams). I recommend a method 
- (id)initWithVariables:(NSDictionary*)parameters language:(NSString *)language;
where "parameters" is a key-value dictionary describing init-only parameters and their values.

**Comment by kevincon** [comment]
Implemented by #113.
