### ISSUE TITLE
How about hOCR?

### ISSUE THREAD

**Issue by BamX** [gali8/Tesseract-OCR-iOS#75]
There is a branch with this small method: https://github.com/clemenshelm/Tesseract-OCR-iOS/commit/15b5f8f2ae8c6325114623100243ef8168796ae8
It may be useful

**Comment by ws233** [comment]
There is an issue in the upstream Tesseract regarding setInputName:
https://code.google.com/p/tesseract-ocr/issues/detail?id=463
it seems that it's already merged to the master, but it's better to check, if we have this in our code.

**Comment by kevincon** [comment]
Nice find! If no one else gets to it, I'll try this tonight to see if it's still necessary to use setInputName.

**Comment by ws233** [comment]
I'm already in progress actually :)
But I'm going to finish work for today soon.
So let me upload things I have for now so you can continue tonight.

**Comment by ws233** [comment]
so #125 can be a good starting point for you.
There are comments about what's already done there.
I'll come back to this tomorrow.

**Comment by clemenshelm** [comment]
Hi! I think I had to use `setInputName` because it didn't work otherwise (as mentioned by @ws233 ). Hopefully this is fixed now and isn't needed anymore.

**Comment by kevincon** [comment]
Feature added with #125.
